// 「キーワードをながめる」で表示する重要語。docs.js の資料パスごとに書く。
// term が大きく表示される用語、desc がその下に出る短い説明。
window.KEYWORDS = [
  // ---- IPアドレス ----
  { doc: "network/ip-address/subnet-cheatsheet.md", term: "ブロック幅", desc: "1ネットワークに含まれるアドレス数。256 − マスク値 で求める（/29 → 256 − 248 = 8）" },
  { doc: "network/ip-address/subnet-cheatsheet.md", term: "使用可能ホスト数", desc: "ブロック幅 − 2（ネットワークアドレスとブロードキャストは使えない）" },
  { doc: "network/ip-address/subnet-cheatsheet.md", term: "ネットワークアドレス", desc: "（対象オクテット ÷ ブロック幅 の商）× ブロック幅" },
  { doc: "network/ip-address/subnet-cheatsheet.md", term: "ブロードキャストアドレス", desc: "ネットワークアドレス ＋ ブロック幅 − 1" },
  { doc: "network/ip-address/ipaddr.md", term: "/27 = 255.255.255.224", desc: "第4オクテットは 11100000。ブロック幅32、使えるホストは30" },
  { doc: "network/ip-address/ipaddr.md", term: "/18 = 255.255.192.0", desc: "第3オクテットが64刻み。アドレス数は 2^14 = 16384" },

  // ---- LAN・L2 ----
  { doc: "network/lan/ethernet-types.md", term: "1000BASE-T", desc: "ギガビットイーサネット（1Gbps）。数字が速度、-T はツイストペアケーブル" },
  { doc: "network/lan/ethernet-types.md", term: "マルチギガビットイーサネット", desc: "2.5GBASE-T / 5GBASE-T" },
  { doc: "network/lan/ethernet-types.md", term: "-SR / -SX / -LR / -LX", desc: "光ファイバーを使うイーサネット規格に付く表記" },

  { doc: "network/lan/poe.md", term: "PoE", desc: "LANケーブルでデータと同時に電源を供給。無線APやIP電話機で使う" },
  { doc: "network/lan/poe.md", term: "IEEE 802.3af", desc: "PoE。最大 15.4W" },
  { doc: "network/lan/poe.md", term: "IEEE 802.3at", desc: "PoE+。最大 30W" },
  { doc: "network/lan/poe.md", term: "IEEE 802.3bt", desc: "PoE++。最大 90W（資料により 60W / 99W）" },

  { doc: "network/lan/ieee802x.md", term: "IEEE 802.11i", desc: "暗号化アルゴリズムに AES を初めて採用。WPA2 が準拠" },
  { doc: "network/lan/ieee802x.md", term: "IEEE 802.1X", desc: "LAN / 無線LANの認証。サプリカント・オーセンティケータ・認証サーバで構成" },
  { doc: "network/lan/ieee802x.md", term: "サプリカント", desc: "802.1X で認証を受ける端末（クライアント）" },
  { doc: "network/lan/ieee802x.md", term: "オーセンティケータ", desc: "802.1X で認証を中継する機器（スイッチ・アクセスポイント）" },
  { doc: "network/lan/ieee802x.md", term: "IEEE 802.1Q", desc: "VLANタグの標準フォーマット" },

  { doc: "network/lan/lag-stp.md", term: "LAG", desc: "複数のリンクを束ねて1つの論理リンクに。帯域拡大と冗長化。Static か LACP で構成" },
  { doc: "network/lan/lag-stp.md", term: "BPDU", desc: "STP の制御フレーム。宛先 MAC は 01:80:C2:00:00:00" },
  { doc: "network/lan/lag-stp.md", term: "ルートブリッジ", desc: "ブリッジID（プライオリティ＋MACアドレス）が最小のスイッチ" },
  { doc: "network/lan/lag-stp.md", term: "パスコスト", desc: "10Gbps = 2 / 1Gbps = 4 / 100Mbps = 19 / 10Mbps = 100" },
  { doc: "network/lan/lag-stp.md", term: "Root Port (RP)", desc: "ルートブリッジに最も近いポート。BPDU を受信。Forwarding" },
  { doc: "network/lan/lag-stp.md", term: "Designated Port (DP)", desc: "各リンクに1つ選出。BPDU を送信。Forwarding" },
  { doc: "network/lan/lag-stp.md", term: "Non Designated Port (NDP)", desc: "RP にも DP にも選ばれなかったポート。Blocking" },
  { doc: "network/lan/lag-stp.md", term: "Listening → Learning → Forwarding", desc: "Learning で MAC 学習を開始、Forwarding でデータ転送も可能になる" },
  { doc: "network/lan/lag-stp.md", term: "RSTP（IEEE 802.1w）", desc: "STP の高速版。AP（RPの予備）と BP（DPの予備）を持つ" },
  { doc: "network/lan/lag-stp.md", term: "MSTP（IEEE 802.1s）", desc: "複数VLANをまとめたインスタンス毎にツリーを構築。負荷分散も可能" },

  { doc: "network/lan/vlan-vxlan.md", term: "TPID = 0x8100", desc: "802.1Q タグ付きフレームであることを示す固定値" },
  { doc: "network/lan/vlan-vxlan.md", term: "PCP", desc: "VLANヘッダの優先度（0〜7）。QoS の CoS で使う" },
  { doc: "network/lan/vlan-vxlan.md", term: "VID", desc: "VLAN ID。12bit で 0〜4095" },
  { doc: "network/lan/vlan-vxlan.md", term: "VXLAN", desc: "L3 ネットワーク上に仮想的な L2 を作るトンネリング。UDP 4789" },
  { doc: "network/lan/vlan-vxlan.md", term: "VNI", desc: "VXLAN のネットワーク識別子。24bit・約1677万" },
  { doc: "network/lan/vlan-vxlan.md", term: "VTEP", desc: "VXLAN トンネルの終端。Loopback にアドレスを割り当てることが多い" },
  { doc: "network/lan/vlan-vxlan.md", term: "Flood & Learn", desc: "Multicast を使って VTEP と VM の紐づけを学習" },
  { doc: "network/lan/vlan-vxlan.md", term: "EVPN", desc: "MP-BGP で VTEP と VM の紐づけを学習。最初からマルチキャストが不要" },
  { doc: "network/lan/vlan-vxlan.md", term: "BUM", desc: "Broadcast ＋ Unknown-Unicast ＋ Multicast。フラッディングされる通信" },
  { doc: "network/lan/vlan-vxlan.md", term: "Ingress Replication", desc: "BUM を必要な VTEP にだけユニキャストで複製して送る" },
  { doc: "network/lan/vlan-vxlan.md", term: "Leaf-Spine 構成", desc: "全 Leaf が全 Spine に接続。サーバー間通信の多いデータセンター向け" },

  { doc: "network/lan/wifi.md", term: "Wi-Fi4 / Wi-Fi5 / Wi-Fi6", desc: "802.11n / 802.11ac / 802.11ax" },
  { doc: "network/lan/wifi.md", term: "OFDM", desc: "チャネルをサブキャリアに分割し、1クライアントの信号を並列に送る" },
  { doc: "network/lan/wifi.md", term: "OFDMA", desc: "サブキャリアをグループ化して複数クライアントと同時に通信（Wi-Fi6）" },
  { doc: "network/lan/wifi.md", term: "SU-MIMO / MU-MIMO", desc: "802.11n は SU-MIMO、802.11ac から MU-MIMO" },
  { doc: "network/lan/wifi.md", term: "BSSID", desc: "1つのAP配下のネットワーク（BSS）の識別子。APのMACアドレスが多い" },
  { doc: "network/lan/wifi.md", term: "ESSID（SSID）", desc: "複数のBSSからなるネットワーク（ESS）の識別子。複数APに同じSSIDを設定" },
  { doc: "network/lan/wifi.md", term: "ビーコン信号", desc: "APが定期的に発信し、自分の存在をクライアントに知らせる" },
  { doc: "network/lan/wifi.md", term: "ローミング", desc: "同一 ESS 内でクライアントが BSS 間を移動すること" },
  { doc: "network/lan/wifi.md", term: "SAE（WPA3）", desc: "PSK と公開鍵暗号を組み合わせた鍵交換。端末ごとの個別暗号化" },
  { doc: "network/lan/wifi.md", term: "WEP / WPA / WPA2", desc: "RC4 / TKIP / AES" },

  // ---- WAN・VPN ----
  { doc: "network/wan-vpn/wan-vpn.md", term: "専用線", desc: "L1。物理的に専用の回線が必要" },
  { doc: "network/wan-vpn/wan-vpn.md", term: "広域イーサネット", desc: "L2。802.1Q タグVLANで通信事業者の回線を利用" },
  { doc: "network/wan-vpn/wan-vpn.md", term: "IP-VPN", desc: "L3。通信事業者の閉域IP網。MPLS を利用。インターネットは経由しない" },
  { doc: "network/wan-vpn/wan-vpn.md", term: "SSL-VPN リバースプロキシ型", desc: "Webブラウザが必要" },
  { doc: "network/wan-vpn/wan-vpn.md", term: "SSL-VPN ポートフォワーディング型", desc: "事前にIPとポートを定義。動的にポートが変わるアプリは使えない" },
  { doc: "network/wan-vpn/wan-vpn.md", term: "SSL-VPN L2フォワーディング型", desc: "仮想NIC経由。ブラウザ非対応や動的ポートのアプリもOK" },

  { doc: "network/wan-vpn/mpls.md", term: "MPLS", desc: "4 Byte のラベルでパケットを転送。IPヘッダ(20Byte)参照より高速" },
  { doc: "network/wan-vpn/mpls.md", term: "CE / PE", desc: "CE = 顧客側の出口ルーター、PE = プロバイダ側の入口ルーター" },
  { doc: "network/wan-vpn/mpls.md", term: "LER / LSR", desc: "LER = ラベルの Insert・Untag、LSR = Insert・Swap・Remove" },
  { doc: "network/wan-vpn/mpls.md", term: "LSP", desc: "ラベルが付与されたパケットが辿る経路" },
  { doc: "network/wan-vpn/mpls.md", term: "FEC", desc: "MPLS で同じ転送処理を行うパケットのグループ" },
  { doc: "network/wan-vpn/mpls.md", term: "Insert / Swap / Remove / Untag", desc: "付与 / 付け替え / 1つ除去 / すべて除去" },

  { doc: "network/wan-vpn/ipsec.md", term: "AH", desc: "IPプロトコル番号 51。改ざん検知のみで暗号化はできない" },
  { doc: "network/wan-vpn/ipsec.md", term: "ESP", desc: "IPプロトコル番号 50。改ざん検知＋暗号化" },
  { doc: "network/wan-vpn/ipsec.md", term: "IKE", desc: "UDP 500 / 4500。DH で鍵交換し SA を確立" },
  { doc: "network/wan-vpn/ipsec.md", term: "SA", desc: "暗号化通信のトンネル。1方向なので最低2本必要" },
  { doc: "network/wan-vpn/ipsec.md", term: "トランスポートモード", desc: "ペイロードのみ暗号化。クライアント・サーバー間などのホスト間通信" },
  { doc: "network/wan-vpn/ipsec.md", term: "トンネルモード", desc: "元のIPヘッダごと暗号化し新IPヘッダを付加。拠点間VPN" },
  { doc: "network/wan-vpn/ipsec.md", term: "NATトラバーサル", desc: "ESP に UDP ヘッダ（ポート 4500）を追加して NAPT を通過させる" },
  { doc: "network/wan-vpn/ipsec.md", term: "ISAKMP", desc: "IPsec の SA 確立・鍵交換の枠組み。IKE のベース" },
  { doc: "network/wan-vpn/ipsec.md", term: "Main Mode / Aggressive Mode", desc: "IKEv1 Phase1。6メッセージでIPも認証 / 3メッセージでIPは認証しない" },
  { doc: "network/wan-vpn/ipsec.md", term: "Quick Mode", desc: "IKEv1 Phase2。3メッセージで IPsec SA を確立" },
  { doc: "network/wan-vpn/ipsec.md", term: "IKEv2", desc: "Phase・Mode の概念なし。4メッセージで IKE SA と IPsec SA を確立" },
  { doc: "network/wan-vpn/ipsec.md", term: "SPI", desc: "ESPヘッダのセキュリティパラメータインデックス" },
  { doc: "network/wan-vpn/ipsec.md", term: "HMAC", desc: "ESP認証データ。パケットの完全性と送信元を検証" },
  { doc: "network/wan-vpn/ipsec.md", term: "Rekey", desc: "Lifetime に従って定期的に暗号化鍵を更新" },

  { doc: "network/wan-vpn/ppp.md", term: "PPP", desc: "1:1 接続で使うデータリンク層のプロトコル。PAP / CHAP で認証" },
  { doc: "network/wan-vpn/ppp.md", term: "PAP", desc: "IDとパスワードを平文でやり取り" },
  { doc: "network/wan-vpn/ppp.md", term: "CHAP", desc: "チャレンジ（乱数）＋パスワードを MD5 でハッシュ化。盗聴に強い" },
  { doc: "network/wan-vpn/ppp.md", term: "PPPoE", desc: "Ethernet 上で PPP を使う。ヘッダ6バイト。フレッツ光など" },
  { doc: "network/wan-vpn/ppp.md", term: "EAP", desc: "PPP を拡張した認証。IEEE 802.1X で使われる" },
  { doc: "network/wan-vpn/ppp.md", term: "PPTP", desc: "PPP を応用した VPN の L2 トンネリングプロトコル" },

  // ---- ルーティング ----
  { doc: "network/routing/igp.md", term: "RIP", desc: "ホップ数で経路選択。30秒ごとに更新、16ホップで到達不能" },
  { doc: "network/routing/igp.md", term: "ルートポイズニング", desc: "到達不能になったルートをホップ数16で通知" },
  { doc: "network/routing/igp.md", term: "スプリットホライズン", desc: "学習したインターフェースへその経路を送り返さない" },
  { doc: "network/routing/igp.md", term: "ポイズンリバース", desc: "無効になった情報を逆方向へ送信。スプリットホライズンより優先" },
  { doc: "network/routing/igp.md", term: "OSPF のエリア", desc: "エリア0がバックボーン。エリア内のルータはエリア内の情報だけを持つ" },
  { doc: "network/routing/igp.md", term: "DR / BDR", desc: "指名ルータ / 副指名ルータ。リンクステート情報を集めて伝播" },
  { doc: "network/routing/igp.md", term: "ABR / ASBR", desc: "エリア境界ルーター / AS境界ルーター" },
  { doc: "network/routing/igp.md", term: "LSA Type1 / Type2", desc: "ルーターLSA（全ルータ）/ ネットワークLSA（DR が生成）" },
  { doc: "network/routing/igp.md", term: "LSA Type3 / 4 / 5", desc: "ネットワークサマリー（ABR）/ ASBRサマリー（ABR）/ AS外部（ASBR）" },

  { doc: "network/routing/bgp.md", term: "BGP", desc: "AS 間の経路制御。TCP 179" },
  { doc: "network/routing/bgp.md", term: "OPEN / UPDATE / NOTIFICATION / KEEPALIVE", desc: "セッション確立 / 経路の広告・更新 / エラー通知 / 生存確認" },
  { doc: "network/routing/bgp.md", term: "AS_PATH", desc: "通過したASのリスト。ループ検出とプリペンドに使う" },
  { doc: "network/routing/bgp.md", term: "LOCAL_PREF", desc: "同一 AS 内での優先度。高いほど優先" },
  { doc: "network/routing/bgp.md", term: "MED", desc: "他 AS からの入口の優先度。低いほど優先" },
  { doc: "network/routing/bgp.md", term: "AS_PATHプリペンド", desc: "自AS番号を複数回追加して経路を選ばれにくくする" },
  { doc: "network/routing/bgp.md", term: "as-override / allowas-in", desc: "広報時に相手のAS番号を自ASに書き換え / 自ASを含む経路も受け入れる" },
  { doc: "network/routing/bgp.md", term: "ルートリフレクタ", desc: "iBGP のフルメッシュを不要にする。複数あればクラスターIDでループ防止" },
  { doc: "network/routing/bgp.md", term: "プライベートAS番号", desc: "64,512〜65,535（2Byte）/ 4,200,000,000〜（4Byte）" },

  { doc: "network/routing/reliability.md", term: "ECMP", desc: "同じコストの複数経路を同時に利用。ハッシュでフロー単位に振り分ける" },
  { doc: "network/routing/reliability.md", term: "BFD", desc: "50ms など短い間隔の死活監視で、高速に障害を検知" },

  { doc: "network/routing/multicast.md", term: "224.0.0.1 / 224.0.0.2", desc: "全ホスト宛 / 全ルータ宛" },
  { doc: "network/routing/multicast.md", term: "224.0.0.5 / 224.0.0.6", desc: "全 OSPF ルータ宛 / 全 OSPF DR・BDR 宛" },
  { doc: "network/routing/multicast.md", term: "224.0.0.18", desc: "VRRP 用" },
  { doc: "network/routing/multicast.md", term: "224.0.0.13 / 224.0.0.22", desc: "PIM 用 / IGMP 用" },
  { doc: "network/routing/multicast.md", term: "239.0.0.0〜239.255.255.255", desc: "プライベートなマルチキャスト。企業内の映像配信など" },
  { doc: "network/routing/multicast.md", term: "01-00-5E", desc: "マルチキャストMACの先頭。IPアドレスの下位23bitをコピーする" },
  { doc: "network/routing/multicast.md", term: "PIM", desc: "マルチキャスト用ルーティング。経路はディストリビューションツリー" },
  { doc: "network/routing/multicast.md", term: "PIM-DM", desc: "Flood & Prune。受信端末が密集した環境（LAN）向け" },
  { doc: "network/routing/multicast.md", term: "PIM-SM", desc: "RP（Rendezvous Point）と join。受信端末が分散した環境（WAN）向け" },
  { doc: "network/routing/multicast.md", term: "PIM-SSM", desc: "配信元IPを指定してツリーを構築。IGMPv3 のソースフィルタが必要" },
  { doc: "network/routing/multicast.md", term: "IGMP", desc: "マルチキャストグループへの参加・脱退を管理" },
  { doc: "network/routing/multicast.md", term: "IGMPv2", desc: "Leave Group で明示的に脱退。Specific Membership Query で残りを確認" },
  { doc: "network/routing/multicast.md", term: "IGMPv3", desc: "ソースフィルタ（配信元IPの指定）が可能" },

  // ---- 冗長化・負荷分散 ----
  { doc: "network/redundancy/vrrp.md", term: "VRRP", desc: "複数ルーターで仮想IP・仮想MACを共有するゲートウェイの冗長化" },
  { doc: "network/redundancy/vrrp.md", term: "VRRPアドバタイズメント", desc: "Master が 224.0.0.18 へ定期送信。Master 選出とダウン検知に使う" },
  { doc: "network/redundancy/vrrp.md", term: "VRID", desc: "VRRP グループの ID。グループ内で Master / Backup を選出" },
  { doc: "network/redundancy/vrrp.md", term: "Master の選出", desc: "Priority が最大 → 同じなら実IPアドレスが最大のルーター" },
  { doc: "network/redundancy/vrrp.md", term: "Preempt", desc: "より高い Priority のルーターが現れたら Master になる" },

  { doc: "network/redundancy/load-balancer.md", term: "ロードバランサーの基本機能", desc: "負荷分散 / セッション維持 / 死活監視" },
  { doc: "network/redundancy/load-balancer.md", term: "セッションアフィニティ", desc: "同じクライアントを同じサーバーへ。IPベース / Cookieベース / URLパラメーター" },
  { doc: "network/redundancy/load-balancer.md", term: "SSL/TLS アクセラレーター", desc: "サーバーの代わりに SSL/TLS を終端。Cookie ベースのセッション維持と併用" },
  { doc: "network/redundancy/load-balancer.md", term: "プローブ", desc: "死活監視の通信。ICMP(L3) / TCP・UDP(L4) / HTTP・HTTPS(L7)" },
  { doc: "network/redundancy/load-balancer.md", term: "ワンアーム構成", desc: "LB にネットワーク経由で間接的に接続。スケーラビリティに優れる" },
  { doc: "network/redundancy/load-balancer.md", term: "DSR", desc: "戻りの通信を LB を経由せず直接クライアントへ。サーバーは Loopback に VIP" },
  { doc: "network/redundancy/load-balancer.md", term: "GSLB", desc: "DNS で送信元に最も近いエッジサーバーへ誘導" },

  // ---- 運用管理 ----
  { doc: "network/operation/qos.md", term: "ポリシング", desc: "入力トラフィックの超過分を破棄" },
  { doc: "network/operation/qos.md", term: "シェーピング", desc: "出力が基準値を超えないよう、送信間隔を調整" },
  { doc: "network/operation/qos.md", term: "IntServ / RSVP", desc: "フロー毎に帯域を予約。厳密だが大規模には不向き" },
  { doc: "network/operation/qos.md", term: "DiffServ", desc: "クラスごとに優先度を制御。現在の主流" },
  { doc: "network/operation/qos.md", term: "CoS", desc: "L2 の優先度。802.1Q の PCP、3bit・8クラス" },
  { doc: "network/operation/qos.md", term: "DSCP", desc: "L3 の優先度。IPヘッダ ToS の 6bit・64クラス" },
  { doc: "network/operation/qos.md", term: "IP Precedence", desc: "ToS の上位 3bit（優先度ビット）だけを使う" },

  { doc: "network/operation/monitoring.md", term: "LLDP", desc: "隣接機器に自身の情報を通知する L2 プロトコル。IEEE 802.1ab" },
  { doc: "network/operation/monitoring.md", term: "SNMP", desc: "UDP 161（Manager → Agent）/ UDP 162（Agent → Manager）" },
  { doc: "network/operation/monitoring.md", term: "MIB / OID", desc: "Agent が管理する情報の集合 / その各情報の識別子" },
  { doc: "network/operation/monitoring.md", term: "Trap / Inform-Request", desc: "Agent からの自発的な通知 / 確認応答つきの通知（v2c〜）" },
  { doc: "network/operation/monitoring.md", term: "Get-Bulk-Request", desc: "複数の OID をまとめて要求（v2c〜）" },
  { doc: "network/operation/monitoring.md", term: "SNMPv3", desc: "コミュニティではなくユーザー単位の認証・暗号化" },
  { doc: "network/operation/monitoring.md", term: "Syslog", desc: "ネットワーク経由でログを転送。UDP 514" },
  { doc: "network/operation/monitoring.md", term: "NetFlow / IPFIX", desc: "フローを監視・分析。IPFIX は UDP/TCP 4739" },

  // ---- プロトコル ----
  { doc: "network/protocol/tcp.md", term: "SYN / FIN / RST", desc: "コネクションの開始 / 終了 / 強制終了" },
  { doc: "network/protocol/tcp.md", term: "ACK番号", desc: "受け取ったシーケンス番号 ＋ 受け取ったデータサイズ" },
  { doc: "network/protocol/tcp.md", term: "ウィンドウ制御", desc: "Ack を待たずにウィンドウサイズ分まとめて送る" },
  { doc: "network/protocol/tcp.md", term: "スライディングウィンドウ", desc: "Ack を得た分だけウィンドウをずらして次を送る" },
  { doc: "network/protocol/tcp.md", term: "フロー制御", desc: "受信側が負荷に応じてウィンドウサイズを変える" },
  { doc: "network/protocol/tcp.md", term: "ウィンドウプローブ", desc: "Window=0 の後、送信側が最新のウィンドウサイズを問い合わせる" },
  { doc: "network/protocol/tcp.md", term: "CWR / ECE", desc: "輻輳ウィンドウを減らした通知 / 輻輳発生の通知（RFC 9293 で追加）" },

  { doc: "network/protocol/udp.md", term: "UDPヘッダ", desc: "8 Byte 固定。送信元ポート・宛先ポート・Length・Checksum" },

  { doc: "network/protocol/well-known-ports.md", term: "20・21 / 22 / 23", desc: "FTP（データ・制御）/ SSH / Telnet" },
  { doc: "network/protocol/well-known-ports.md", term: "25 / 587", desc: "SMTP / SMTPサブミッション（STARTTLS）" },
  { doc: "network/protocol/well-known-ports.md", term: "110 / 995", desc: "POP3 / POP3S" },
  { doc: "network/protocol/well-known-ports.md", term: "143 / 993", desc: "IMAP / IMAPS" },
  { doc: "network/protocol/well-known-ports.md", term: "53 / 67・68 / 123", desc: "DNS / DHCP（サーバ・クライアント）/ NTP" },
  { doc: "network/protocol/well-known-ports.md", term: "161・162 / 514", desc: "SNMP / Syslog" },
  { doc: "network/protocol/well-known-ports.md", term: "179 / 443 / 445", desc: "BGP / HTTPS / SMB" },

  { doc: "network/protocol/dhcp.md", term: "DHCP", desc: "IPアドレスなどを自動で割り当てる。UDP 67（サーバ）/ 68（クライアント）" },
  { doc: "network/protocol/dhcp.md", term: "Discover → Offer → Request → ACK", desc: "DHCP のメッセージの順番。Discover はブロードキャスト" },
  { doc: "network/protocol/dhcp.md", term: "リース期間", desc: "割り当てたIPアドレスの有効期間。終了時にクライアントが更新を要求" },

  { doc: "network/protocol/http.md", term: "401 / 403 / 404", desc: "認証情報が無効 / 権限不足 / リソースが存在しない" },
  { doc: "network/protocol/http.md", term: "429", desc: "短期間にリクエストを送りすぎ（レートリミット超過）" },
  { doc: "network/protocol/http.md", term: "500 / 502", desc: "サーバー内部エラー / ゲートウェイがサーバーから無効な応答を受信" },
  { doc: "network/protocol/http.md", term: "301 / 302", desc: "恒久的なリダイレクト / 一時的なリダイレクト" },
  { doc: "network/protocol/http.md", term: "X-Forwarded-For", desc: "プロキシ経由でも送信元IPアドレスをWebサーバーに伝える" },
  { doc: "network/protocol/http.md", term: "Secure 属性", desc: "HTTPS 通信のときだけ Cookie を送る" },
  { doc: "network/protocol/http.md", term: "Basic 認証 / Digest 認証", desc: "Base64 でエンコード / ハッシュ化して送信" },
  { doc: "network/protocol/http.md", term: "HTTP/2", desc: "バイナリ・ストリーム多重化・ヘッダ圧縮(HPACK)・サーバープッシュ" },
  { doc: "network/protocol/http.md", term: "HTTP/3（QUIC）", desc: "UDP ベース。1往復で接続確立と暗号化を同時に行う" },

  { doc: "network/protocol/tls.md", term: "TLS 1.3", desc: "RSA鍵交換を廃止し (EC)DHE を使う。2往復目から暗号化通信" },
  { doc: "network/protocol/tls.md", term: "前方秘匿性", desc: "セッション終了後に過去の通信内容を復号できない性質" },
  { doc: "network/protocol/tls.md", term: "AEAD", desc: "認証付き暗号。暗号化と同時に改ざん検知" },
  { doc: "network/protocol/tls.md", term: "key_share", desc: "TLS 1.3 の Hello で交換する共通鍵のもと" },
  { doc: "network/protocol/tls.md", term: "Client Key Exchange", desc: "TLS 1.2 でプリマスターシークレットを送るメッセージ" },

  { doc: "network/protocol/email-header.md", term: "Return-Path", desc: "配送に失敗したときのエラーメールの送信先" },
  { doc: "network/protocol/email-header.md", term: "Received", desc: "メールの転送経路。下から上へたどる（上が新しい）" },
  { doc: "network/protocol/email-header.md", term: "Reply-To", desc: "返信するときの返信先アドレス" },

  { doc: "network/protocol/mail-security.md", term: "SPF", desc: "送信を許可するサーバを DNS（TXT）に登録。-all = 失敗 / ~all = ソフトフェイル" },
  { doc: "network/protocol/mail-security.md", term: "DKIM", desc: "メールにデジタル署名を付け、DNS の公開鍵で検証" },
  { doc: "network/protocol/mail-security.md", term: "DMARC", desc: "SPF / DKIM の結果に基づく処理ポリシー（none / quarantine / reject）" },
  { doc: "network/protocol/mail-security.md", term: "rua / ruf", desc: "アグリゲートレポート / フォレンジックレポートの送信先" },

  { doc: "network/protocol/voip.md", term: "SIP", desc: "呼制御（シグナリング）。REGISTER / INVITE / ACK / BYE" },
  { doc: "network/protocol/voip.md", term: "SDP", desc: "SIP で交換するメディア情報（音声/動画・ポート番号など）の形式" },
  { doc: "network/protocol/voip.md", term: "RTP / RTCP", desc: "音声データの転送（UDP）/ 品質情報のフィードバック" },
  { doc: "network/protocol/voip.md", term: "ジッター", desc: "パケットの到着時間のばらつき" },
  { doc: "network/protocol/voip.md", term: "標本化 → 量子化 → 符号化", desc: "音声をデジタルデータにする3つの工程" },
  { doc: "network/protocol/voip.md", term: "標本化定理", desc: "信号の周波数の2倍以上でサンプリング（4kHz → 8kHz）" },
  { doc: "network/protocol/voip.md", term: "PCM / CS-ACELP", desc: "64 kbps / 8 kbps（CS-ACELP は音質が劣る）" },
  { doc: "network/protocol/voip.md", term: "IP-PBX / VoIPゲートウェイ", desc: "IP網でのPBX / 電話線のアナログをデジタルに変換" },
];
