// 四択問題のデータ。docs.js の資料パスごとに問題を書く。
// answer が正解、wrong が不正解の選択肢（3つ以上）。表示時に選択肢の順番はシャッフルされる。
// explain は解答後に表示される解説。
// 問題文(q)を書き換えると、その問題の成績記録はリセットされる。
window.QUIZ_QUESTIONS = [
  // ---- IPアドレス ----
  { doc: "network/ip-address/subnet-cheatsheet.md", q: "/29 のブロック幅（1ネットワークに含まれるアドレス数）はいくつか。", answer: "8", wrong: ["4", "16", "32"], explain: "/29 の該当オクテットのマスクは 248。256 − 248 = 8。" },
  { doc: "network/ip-address/subnet-cheatsheet.md", q: "220.7.39.150/29 のネットワークアドレスはどれか。", answer: "220.7.39.144", wrong: ["220.7.39.148", "220.7.39.150", "220.7.39.152"], explain: "ブロック幅8。150 ÷ 8 = 18 余り 6 → 18 × 8 = 144。" },
  { doc: "network/ip-address/subnet-cheatsheet.md", q: "220.7.39.150/29 のブロードキャストアドレスはどれか。", answer: "220.7.39.151", wrong: ["220.7.39.150", "220.7.39.152", "220.7.39.159"], explain: "ネットワークアドレス144 + ブロック幅8 − 1 = 151。" },
  { doc: "network/ip-address/subnet-cheatsheet.md", q: "169.28.203.42/21 のネットワークアドレスはどれか。", answer: "169.28.200.0", wrong: ["169.28.203.0", "169.28.196.0", "169.28.208.0"], explain: "/21 は第3オクテットのブロック幅8。203 ÷ 8 = 25 → 25 × 8 = 200。第4オクテットは0。" },
  { doc: "network/ip-address/subnet-cheatsheet.md", q: "/27 のネットワークで使用可能なホスト数はいくつか。", answer: "30", wrong: ["32", "62", "14"], explain: "ブロック幅は 2^(32−27) = 32。ネットワークアドレスとブロードキャストを除いて 32 − 2 = 30。" },
  { doc: "network/ip-address/subnet-cheatsheet.md", q: "169.28.203.42/21 のブロードキャストアドレスはどれか。", answer: "169.28.207.255", wrong: ["169.28.203.255", "169.28.207.0", "169.28.208.255"], explain: "第3オクテットは 200 + 8 − 1 = 207。第3オクテットをまたぐ場合、第4オクテットは丸ごと255になる。" },

  { doc: "network/ip-address/ipaddr.md", q: "/27 のサブネットマスクを10進数で表したものはどれか。", answer: "255.255.255.224", wrong: ["255.255.255.192", "255.255.255.240", "255.255.255.248"], explain: "第4オクテットの上位3bitが1 → 11100000 = 128 + 64 + 32 = 224。" },
  { doc: "network/ip-address/ipaddr.md", q: "172.17.10.128/27 のブロードキャストアドレスはどれか。", answer: "172.17.10.159", wrong: ["172.17.10.143", "172.17.10.191", "172.17.10.255"], explain: "ブロック幅32。128 + 32 − 1 = 159。" },
  { doc: "network/ip-address/ipaddr.md", q: "172.17.10.128/27 で最後に使用可能なIPアドレスはどれか。", answer: "172.17.10.158", wrong: ["172.17.10.159", "172.17.10.157", "172.17.10.160"], explain: "ブロードキャスト(159)の1つ手前の158が最後に割り当て可能なアドレス。" },
  { doc: "network/ip-address/ipaddr.md", q: "192.168.100.0/18 が属するネットワークのネットワークアドレスはどれか。", answer: "192.168.64.0", wrong: ["192.168.0.0", "192.168.96.0", "192.168.100.0"], explain: "/18 の第3オクテットは 256 − 192 = 64 刻み。100 は 64以上128未満なので開始は64。" },
  { doc: "network/ip-address/ipaddr.md", q: "/18 のネットワークに含まれるIPアドレスの個数はいくつか。", answer: "16384", wrong: ["8192", "32768", "4096"], explain: "ホスト部は 32 − 18 = 14bit。2^14 = 16384。" },

  // ---- LAN・L2 ----
  { doc: "network/lan/ethernet-types.md", q: "1000BASE-T の伝送速度はどれか。", answer: "1Gbps", wrong: ["100Mbps", "10Gbps", "2.5Gbps"], explain: "数字部分が転送速度を表す。1000BASE-T はギガビットイーサネット。" },
  { doc: "network/lan/ethernet-types.md", q: "2.5GBASE-T や 5GBASE-T の呼称として正しいものはどれか。", answer: "マルチギガビットイーサネット", wrong: ["ギガビットイーサネット", "10ギガビットイーサネット", "ファストイーサネット"], explain: "2.5G/5GBASE-T はマルチギガビットイーサネットと呼ばれる。" },
  { doc: "network/lan/ethernet-types.md", q: "10BASE-T の「-T」や 100BASE-TX の「-TX」が示す媒体はどれか。", answer: "ツイストペアケーブル", wrong: ["マルチモード光ファイバー", "同軸ケーブル", "シングルモード光ファイバー"], explain: "-T / -TX はツイストペアケーブル（LANケーブル）を示す。" },
  { doc: "network/lan/ethernet-types.md", q: "光ファイバーを使うイーサネット規格の末尾に付く表記の例はどれか。", answer: "-SR や -LX", wrong: ["-T や -TX", "-af や -at", "-bt や -ab"], explain: "光ファイバーの場合は -SR, -SX, -LX, -LR などが付く。" },

  { doc: "network/lan/poe.md", q: "IEEE 802.3at（PoE+）の最大供給電力はどれか。", answer: "30W", wrong: ["15.4W", "60W", "90W"], explain: "802.3af(PoE)=15.4W、802.3at(PoE+)=30W、802.3bt(PoE++)=90W（資料による）。" },
  { doc: "network/lan/poe.md", q: "IEEE 802.3af の通称と最大供給電力の組み合わせとして正しいものはどれか。", answer: "PoE / 15.4W", wrong: ["PoE+ / 30W", "PoE++ / 90W", "PoE / 30W"], explain: "802.3af は最初のPoE規格で最大15.4W。" },
  { doc: "network/lan/poe.md", q: "PoE の説明として正しいものはどれか。", answer: "UTPケーブル(LANケーブル)を使ってデータと同時に電源を供給する技術", wrong: ["光ファイバーを使って電源を供給する技術", "無線で機器に給電する技術", "USBケーブルでネットワーク機器に給電する技術"], explain: "PoE は Power over Ethernet。無線APやIP電話機などへの給電に使われる。" },
  { doc: "network/lan/poe.md", q: "PoE++ に対応する規格はどれか。", answer: "IEEE 802.3bt", wrong: ["IEEE 802.3at", "IEEE 802.3af", "IEEE 802.1X"], explain: "802.3bt が PoE++。" },

  { doc: "network/lan/ieee802x.md", q: "暗号化アルゴリズムに AES を初めて採用し、WPA2 が準拠する規格はどれか。", answer: "IEEE 802.11i", wrong: ["IEEE 802.1X", "IEEE 802.11ac", "IEEE 802.1Q"], explain: "IEEE 802.11i は WPA2 が準拠するセキュリティ規格。" },
  { doc: "network/lan/ieee802x.md", q: "IEEE 802.1X 認証において、認証を中継するスイッチやアクセスポイントの役割名はどれか。", answer: "オーセンティケータ", wrong: ["サプリカント", "認証サーバ", "ルートブリッジ"], explain: "サプリカント=認証を受ける端末、オーセンティケータ=中継する機器、認証サーバ=RADIUSサーバ等。" },
  { doc: "network/lan/ieee802x.md", q: "VLANタグの標準フォーマットを策定した規格はどれか。", answer: "IEEE 802.1Q", wrong: ["IEEE 802.1X", "IEEE 802.1w", "IEEE 802.3at"], explain: "IEEE 802.1Q がタグVLANの標準。" },
  { doc: "network/lan/ieee802x.md", q: "IEEE 802.11be が使用する周波数帯として正しいものはどれか。", answer: "2.4GHz帯 / 5GHz帯 / 6GHz帯", wrong: ["5GHz帯のみ", "2.4GHz帯 / 5GHz帯", "2.4GHz帯のみ"], explain: "802.11be は 2.4 / 5 / 6GHz帯を使い、最大46Gbps。" },
  { doc: "network/lan/ieee802x.md", q: "IEEE 802.11b の最大伝送速度はどれか。", answer: "11Mbps", wrong: ["54Mbps", "600Mbps", "6.9Gbps"], explain: "802.11b は 2.4GHz帯で最大11Mbps。" },

  { doc: "network/lan/lag-stp.md", q: "複数のリンクを束ねて1つの論理リンクとして扱う技術はどれか。", answer: "LAG（リンクアグリゲーション）", wrong: ["STP", "VRRP", "ECMP"], explain: "LAG は帯域拡大と冗長化を実現し、STPと違いブロッキングポートが生じない。StaticまたはLACPで構成する。" },
  { doc: "network/lan/lag-stp.md", q: "STPでルートブリッジに選出されるスイッチはどれか。", answer: "ブリッジID（プライオリティ＋MACアドレス）が最も小さいスイッチ", wrong: ["ブリッジIDが最も大きいスイッチ", "パスコストが最も小さいスイッチ", "ポートIDが最も小さいスイッチ"], explain: "ブリッジIDが最小のスイッチ。プライオリティ未設定ならMACアドレスの小さいスイッチが選ばれる。" },
  { doc: "network/lan/lag-stp.md", q: "STPのパスコストで、1Gbpsのリンクの値はどれか。", answer: "4", wrong: ["2", "19", "100"], explain: "10Gbps=2 / 1Gbps=4 / 100Mbps=19 / 10Mbps=100。" },
  { doc: "network/lan/lag-stp.md", q: "BPDUの受信のみを行い、データ転送もMACアドレス学習も行わないポートのステータスはどれか。", answer: "Blocking", wrong: ["Listening", "Learning", "Forwarding"], explain: "Listening は BPDU を送受信する状態。Blocking は受信のみ。" },
  { doc: "network/lan/lag-stp.md", q: "MACアドレス学習は行うが、データ転送はまだ行わないポートのステータスはどれか。", answer: "Learning", wrong: ["Listening", "Blocking", "Disabled"], explain: "Listening → Learning（学習のみ）→ Forwarding（転送も可能）の順に遷移する。" },
  { doc: "network/lan/lag-stp.md", q: "各リンクごとに1つ選出され、BPDUの送信を担うポートはどれか。", answer: "Designated Port（指定ポート）", wrong: ["Root Port（ルートポート）", "Non Designated Port（非指定ポート）", "Alternate Port"], explain: "DPは各リンクに1つ。RPはルートブリッジに最も近いポートでBPDUの受信を担う。" },
  { doc: "network/lan/lag-stp.md", q: "RSTP を標準化した規格はどれか。", answer: "IEEE 802.1w", wrong: ["IEEE 802.1s", "IEEE 802.1D", "IEEE 802.1Q"], explain: "RSTP は 802.1w、MSTP は 802.1s。" },
  { doc: "network/lan/lag-stp.md", q: "RSTPで、ルートポート(RP)のバックアップとして動作するポートはどれか。", answer: "Alternate Port (AP)", wrong: ["Backup Port (BP)", "Designated Port (DP)", "Non Designated Port (NDP)"], explain: "AP は RP のバックアップ、BP は DP のバックアップ。NDPの代わりにこれらを設けて高速化している。" },
  { doc: "network/lan/lag-stp.md", q: "複数のVLANをまとめたインスタンス単位でSTPツリーを構築でき、負荷分散も可能なプロトコルはどれか。", answer: "MSTP", wrong: ["RSTP", "STP", "LACP"], explain: "MSTP（IEEE 802.1s）はインスタンス毎にブロッキングポートを調整できる。" },
  { doc: "network/lan/lag-stp.md", q: "BPDUの送信に使われるマルチキャストMACアドレスはどれか。", answer: "01:80:C2:00:00:00", wrong: ["01:80:C2:00:00:0E", "01:00:5E:00:00:01", "FF:FF:FF:FF:FF:FF"], explain: "01:80:C2:00:00:0E は LLDP、01:00:5E で始まるのは IPマルチキャスト用。" },

  { doc: "network/lan/vlan-vxlan.md", q: "IEEE 802.1Q タグVLANフレームの TPID の固定値はどれか。", answer: "0x8100", wrong: ["0x0800", "0x86DD", "0x8847"], explain: "TPID=0x8100 でタグ付きフレームであることを示す。" },
  { doc: "network/lan/vlan-vxlan.md", q: "VLANヘッダの VID のビット数として正しいものはどれか。", answer: "12bit（0〜4095）", wrong: ["3bit（0〜7）", "24bit（約1677万）", "16bit（0〜65535）"], explain: "VIDは12bit。3bitはPCP、24bitはVXLANのVNI。" },
  { doc: "network/lan/vlan-vxlan.md", q: "VXLAN の VNI のビット数と識別できるネットワーク数はどれか。", answer: "24bit・約1677万", wrong: ["12bit・4096", "16bit・約6.5万", "32bit・約43億"], explain: "24bit の VNI で 2^24 = 16,777,216 のL2ネットワークを識別できる。" },
  { doc: "network/lan/vlan-vxlan.md", q: "VXLAN で一般的に使われるポートはどれか。", answer: "UDP 4789", wrong: ["UDP 4500", "TCP 4789", "UDP 4739"], explain: "VXLAN は UDP 4789。UDP 4500 は IPsec の NATトラバーサル、4739 は IPFIX。" },
  { doc: "network/lan/vlan-vxlan.md", q: "VXLANトンネルを終端する役割を持つスイッチやインターフェースを何と呼ぶか。", answer: "VTEP", wrong: ["VNI", "LSR", "PE"], explain: "VTEP (VXLAN Tunnel Endpoint)。障害に備えて Loopback にアドレスを割り当てることが多い。" },
  { doc: "network/lan/vlan-vxlan.md", q: "EVPN が VTEP と VM の紐づけを学習するために使うプロトコルはどれか。", answer: "MP-BGP", wrong: ["Multicast", "OSPF", "LLDP"], explain: "EVPN は MP-BGP で学習するため、Flood & Learn と違い最初からマルチキャスト通信が生じない。" },
  { doc: "network/lan/vlan-vxlan.md", q: "BUMトラフィックの「U」が指すものはどれか。", answer: "Unknown-Unicast", wrong: ["Unicast", "UDP", "Unspecified"], explain: "BUM = Broadcast + Unknown-Unicast + Multicast。フラッディングで転送されるトラフィックの総称。" },
  { doc: "network/lan/vlan-vxlan.md", q: "EVPNで、BUMトラフィックを必要なVTEPだけにユニキャストで複製して送る機能はどれか。", answer: "Ingress Replication", wrong: ["Flood & Learn", "Split Horizon", "Route Reflector"], explain: "Ingress Replication を使うと BUM をマルチキャストではなくユニキャストで送れる。" },
  { doc: "network/lan/vlan-vxlan.md", q: "データセンターで VXLAN を使う主な理由として正しいものはどれか。", answer: "VNIを分けることで、IPアドレスが重複する複数テナントの通信を競合なく転送できる", wrong: ["L2ネットワーク同士をL1の専用線で直結できる", "通信を自動的に暗号化できる", "STPのブロッキングポートを自動で解除できる"], explain: "テナント間でIPアドレス範囲が重複してもVNIで分離できる。Leaf-Spine構成とよく組み合わせる。" },

  { doc: "network/lan/wifi.md", q: "IEEE 802.11ax の名称はどれか。", answer: "Wi-Fi6", wrong: ["Wi-Fi4", "Wi-Fi5", "Wi-Fi7"], explain: "802.11n=Wi-Fi4、802.11ac=Wi-Fi5、802.11ax=Wi-Fi6。" },
  { doc: "network/lan/wifi.md", q: "OFDMA の説明として正しいものはどれか。", answer: "複数のサブキャリアをグループ化して各クライアントに割り当て、複数クライアントと同時に通信する", wrong: ["1つのクライアントからの信号を複数のサブキャリアで送信する", "複数のアンテナで1台の端末と同時に通信する", "隣接チャネルを束ねて帯域幅を広げる"], explain: "OFDMA は 802.11ax のマルチユーザーアクセス技術。1クライアントの信号を複数サブキャリアで送るのは OFDM。" },
  { doc: "network/lan/wifi.md", q: "複数のBSSから構成される無線ネットワーク(ESS)の識別子はどれか。", answer: "ESSID（SSID）", wrong: ["BSSID", "VNI", "VLAN ID"], explain: "ESSはESSID/SSIDで識別する。複数のAPに同じSSIDを付与して構成する。" },
  { doc: "network/lan/wifi.md", q: "BSSID に使われることが多い値はどれか。", answer: "APのMACアドレス", wrong: ["APのIPアドレス", "任意の文字列", "クライアントのMACアドレス"], explain: "1つのAP配下のネットワーク(BSS)の識別子で、APのMACアドレスが使われることが多い。" },
  { doc: "network/lan/wifi.md", q: "WPA3（パーソナル）で使われる鍵交換方式はどれか。", answer: "SAE", wrong: ["PSK", "TKIP", "RC4"], explain: "SAE は PSK と公開鍵暗号を組み合わせた方式で、端末ごとの個別暗号化を実現する。" },
  { doc: "network/lan/wifi.md", q: "2.4GHz帯の特徴として正しいものはどれか。", answer: "障害物に強いが、電子レンジやBluetoothと干渉しやすい", wrong: ["干渉が少なく高速だが、障害物に弱い", "3つの周波数帯の中で最も障害物に弱い", "Wi-Fi6以降でのみ利用できる"], explain: "5GHzや6GHzは干渉が少なく高速だが障害物に弱い。" },
  { doc: "network/lan/wifi.md", q: "WEP が使用する暗号化アルゴリズムはどれか。", answer: "RC4", wrong: ["AES", "TKIP", "SAE"], explain: "WEP=RC4、WPA=TKIP、WPA2/WPA3=AES。WEPとWPAは脆弱なため推奨されない。" },
  { doc: "network/lan/wifi.md", q: "APから定期的に発信され、APの存在をクライアントに知らせる信号はどれか。", answer: "ビーコン信号", wrong: ["BPDU", "VRRPアドバタイズメント", "LLDPフレーム"], explain: "ビーコン信号でクライアントはAPを見つける。" },
  { doc: "network/lan/wifi.md", q: "WLC（ワイヤレスLANコントローラー）がある環境のローミングの特徴はどれか。", answer: "新しいAPが受けた認証要求をWLCに問い合わせて認証を完了する", wrong: ["クライアントが新しいAPに対して毎回ゼロから再認証する", "SSIDの異なるAPへ自動的に移動する", "ローミング中はBSSIDが変わらない"], explain: "WLCがない場合は新しいAPに対して再認証を行う。" },

  // ---- WAN・VPN ----
  { doc: "network/wan-vpn/wan-vpn.md", q: "広域イーサネットが動作するレイヤーと利用する技術の組み合わせはどれか。", answer: "L2 / IEEE 802.1Q のタグVLAN", wrong: ["L3 / MPLS", "L1 / 専用の物理回線", "L4 / SSL-VPN"], explain: "広域イーサネットはL2、IP-VPNはL3でMPLS、専用線はL1。" },
  { doc: "network/wan-vpn/wan-vpn.md", q: "インターネットを経由するサービスはどれか。", answer: "IPsec VPN", wrong: ["専用線", "広域イーサネット", "IP-VPN"], explain: "インターネットVPN（IPsec VPN / SSL-VPN）のみインターネットを経由する。" },
  { doc: "network/wan-vpn/wan-vpn.md", q: "Webブラウザが必要な SSL-VPN の方式はどれか。", answer: "リバースプロキシ型", wrong: ["ポートフォワーディング型", "L2フォワーディング型", "トンネルモード型"], explain: "ポートフォワーディング型とL2フォワーディング型はWebブラウザ不要。" },
  { doc: "network/wan-vpn/wan-vpn.md", q: "動的にポート番号が変わるアプリケーションでも利用できる SSL-VPN の方式はどれか。", answer: "L2フォワーディング型", wrong: ["ポートフォワーディング型", "リバースプロキシ型", "トランスポートモード型"], explain: "L2フォワーディング型は仮想NICを経由するためアプリに依存しない。ポートフォワーディング型は事前にIPとポートの定義が必要。" },

  { doc: "network/wan-vpn/mpls.md", q: "MPLS のラベルのサイズはどれか。", answer: "4 Byte", wrong: ["20 Byte", "2 Byte", "8 Byte"], explain: "ラベルは4 Byteと軽量なため、IPヘッダ(20 Byte)を参照するルーティングより高速に動作する。" },
  { doc: "network/wan-vpn/mpls.md", q: "MPLS でラベルを付け替える操作はどれか。", answer: "Swap", wrong: ["Insert", "Remove", "Untag"], explain: "Insert=付与、Swap=付け替え、Remove=1つ除去、Untag=すべて除去。" },
  { doc: "network/wan-vpn/mpls.md", q: "顧客側でIP網への出口となるルーターはどれか。", answer: "CE（Customer Edge）", wrong: ["PE（Provider Edge）", "LSR（Label Switching Router）", "LER（Label Edge Router）"], explain: "CE は顧客側、PE はプロバイダ側の入り口となるルーター。" },
  { doc: "network/wan-vpn/mpls.md", q: "MPLS において、同じ転送処理を行うパケットのグループを何と呼ぶか。", answer: "FEC", wrong: ["LSP", "VNI", "SA"], explain: "FEC (Forwarding Equivalence Class)。LSP はラベル付きパケットが辿る経路。" },
  { doc: "network/wan-vpn/mpls.md", q: "ラベルをすべて除去する操作はどれか。", answer: "Untag", wrong: ["Remove", "Swap", "Insert"], explain: "Remove はラベルを1つ除去、Untag はすべて除去。" },

  { doc: "network/wan-vpn/ipsec.md", q: "ESP の IPプロトコル番号はどれか。", answer: "50", wrong: ["51", "6", "17"], explain: "ESP=50、AH=51。6はTCP、17はUDP。" },
  { doc: "network/wan-vpn/ipsec.md", q: "AH（Authentication Header）の特徴として正しいものはどれか。", answer: "改ざん検知はできるが、暗号化はできない", wrong: ["改ざん検知と暗号化の両方ができる", "鍵交換を担う", "暗号化はできるが、改ざん検知はできない"], explain: "改ざん検知と暗号化の両方ができるのはESP。鍵交換はIKE。" },
  { doc: "network/wan-vpn/ipsec.md", q: "IKE が使用するポートはどれか。", answer: "UDP 500 または 4500", wrong: ["TCP 443", "UDP 4789", "TCP 500"], explain: "IKE は UDP 500。NATトラバーサル時は UDP 4500。" },
  { doc: "network/wan-vpn/ipsec.md", q: "ESP のトンネルモードで暗号化される範囲はどれか。", answer: "元のIPヘッダを含むIPパケット全体 + ESPトレーラ", wrong: ["IPパケットのペイロード部分 + ESPトレーラ", "新IPヘッダを含むパケット全体", "ESPヘッダと認証データのみ"], explain: "トンネルモードは元のIPヘッダも暗号化され、新しいIPヘッダが付加される。ペイロードのみはトランスポートモード。" },
  { doc: "network/wan-vpn/ipsec.md", q: "拠点間VPNで一般的に使われる ESP のモードはどれか。", answer: "トンネルモード", wrong: ["トランスポートモード", "アグレッシブモード", "クイックモード"], explain: "トランスポートモードはクライアントとサーバー間などエンドツーエンドの通信で使う。" },
  { doc: "network/wan-vpn/ipsec.md", q: "NATトラバーサルで IPsec パケットに追加されるものはどれか。", answer: "ポート4500を使う専用のUDPヘッダ", wrong: ["ポート443を使うTCPヘッダ", "AHヘッダ", "新しいMPLSラベル"], explain: "ESPはポート番号を持たずNAPTを通過できないため、UDPヘッダを追加する。" },
  { doc: "network/wan-vpn/ipsec.md", q: "NATトラバーサルが必要になる理由として正しいものはどれか。", answer: "ESPはL3プロトコルでポート番号情報を持たず、NAPTを適用できないため", wrong: ["ESPはUDPを使うためNAPTで破棄されるため", "IKEがTCPで動作するため", "トランスポートモードではIPヘッダが暗号化されるため"], explain: "加えて、ISAKMP の UDP 500 が NAPT の影響を受けることも理由の一つ。" },
  { doc: "network/wan-vpn/ipsec.md", q: "IKEv1 の Phase1 で、6つのメッセージを使い対向機器のIPアドレスも認証するモードはどれか。", answer: "Main Mode", wrong: ["Aggressive Mode", "Quick Mode", "Transport Mode"], explain: "Aggressive Mode は3メッセージでIPアドレスを認証しない。Quick Mode は Phase2。" },
  { doc: "network/wan-vpn/ipsec.md", q: "IKEv2 で IKE SA と IPsec SA を確立するのに必要なメッセージ数はどれか。", answer: "4つ", wrong: ["6つ", "3つ", "9つ"], explain: "IKEv2 は Phase や Mode の概念がなく、4つのメッセージで両方の SA を確立できる。" },
  { doc: "network/wan-vpn/ipsec.md", q: "SA（Security Association）について正しいものはどれか。", answer: "1方向のみ確立されるため、各フェーズで最低2本必要", wrong: ["双方向なので1本で足りる", "Phase2でのみ確立される", "IKEv2では確立しない"], explain: "SAは暗号化通信のためのトンネル。1方向なので送受信で2本必要。" },
  { doc: "network/wan-vpn/ipsec.md", q: "ESP認証データでパケットの完全性確認に用いられるものはどれか。", answer: "HMAC（ハッシュ値）", wrong: ["SPI", "シーケンス番号", "パディング"], explain: "SPIとシーケンス番号はESPヘッダ、パディングはESPトレーラに含まれる。" },
  { doc: "network/wan-vpn/ipsec.md", q: "IKE で暗号化のための鍵生成に使われる方式はどれか。", answer: "DH（Diffie Hellman）", wrong: ["MD5", "PSK", "AES"], explain: "IKE は DH アルゴリズムで安全に鍵交換を行う。" },

  { doc: "network/wan-vpn/ppp.md", q: "CHAP の説明として正しいものはどれか。", answer: "チャレンジ(乱数)とパスワードをMD5でハッシュ化して返送する", wrong: ["IDとパスワードを平文でやり取りする", "証明書を使って相互認証する", "公開鍵暗号で共通鍵を交換する"], explain: "平文でやり取りするのは PAP。CHAP は盗聴に強い。" },
  { doc: "network/wan-vpn/ppp.md", q: "PPPoE ヘッダのサイズはどれか。", answer: "6バイト", wrong: ["2バイト", "14バイト", "20バイト"], explain: "PPPヘッダ=2バイト、Ethernetヘッダ=14バイト、IPヘッダ=20バイト（オプションで最大60）。" },
  { doc: "network/wan-vpn/ppp.md", q: "PPPoE が必要になる理由として正しいものはどれか。", answer: "Ethernetは認証機能を持たないため", wrong: ["EthernetはIPパケットを運べないため", "PPPは暗号化が必須のため", "Ethernetは1:1の接続しかできないため"], explain: "ISPのユーザー名とパスワードで認証するため、Ethernet上でPPPを使う。" },
  { doc: "network/wan-vpn/ppp.md", q: "PPP を拡張して追加の認証機能を実装し、IEEE 802.1X などで使われるものはどれか。", answer: "EAP", wrong: ["CHAP", "PPTP", "PAP"], explain: "EAP は PPP の拡張。PPTP は PPP を応用した VPN の L2トンネリングプロトコル。" },
  { doc: "network/wan-vpn/ppp.md", q: "PPP が動作するレイヤーはどれか。", answer: "データリンク層（L2）", wrong: ["物理層（L1）", "ネットワーク層（L3）", "トランスポート層（L4）"], explain: "PPP は専用線やISDNなど1:1の接続で使うデータリンク層のプロトコル。" },

  // ---- ルーティング ----
  { doc: "network/routing/igp.md", q: "RIP のルートポイズニングで、到達不能を示すホップ数はどれか。", answer: "16", wrong: ["15", "255", "30"], explain: "情報を流さないのではなく、最大値の16ホップとして通知する。" },
  { doc: "network/routing/igp.md", q: "スプリットホライズンの説明として正しいものはどれか。", answer: "学習した経路情報を、学習したインターフェースへ送り返さない", wrong: ["無効になった経路を逆方向に「無効」として送信する", "到達不能な経路をホップ数16で通知する", "30秒ごとに全経路を送信する"], explain: "「無効」を逆方向に送るのはポイズンリバース（スプリットホライズンより優先）。" },
  { doc: "network/routing/igp.md", q: "RIP の定期更新の間隔はどれか。", answer: "30秒", wrong: ["10秒", "60秒", "90秒"], explain: "30秒ごとの更新のためコンバージェンスが遅い。" },
  { doc: "network/routing/igp.md", q: "クラスレスに対応した RIP のバージョンはどれか。", answer: "RIPv2", wrong: ["RIPv1", "RIPng", "RIPv3"], explain: "RIPv1はクラスフル、RIPngはIPv6用。" },
  { doc: "network/routing/igp.md", q: "OSPF で指名ルータ(DR)が生成する LSA はどれか。", answer: "Type2（ネットワークLSA）", wrong: ["Type1（ルーターLSA）", "Type3（ネットワークサマリーLSA）", "Type5（AS外部LSA）"], explain: "Type1は全OSPFルータ、Type3/4はABR、Type5はASBRが生成する。" },
  { doc: "network/routing/igp.md", q: "OSPF で AS外部LSA（Type5）を生成するルーターはどれか。", answer: "ASBR", wrong: ["ABR", "DR", "BDR"], explain: "ASBR（AS境界ルーター）がOSPFドメイン外の経路情報を提供する。" },
  { doc: "network/routing/igp.md", q: "OSPF のバックボーンエリアのエリア番号はどれか。", answer: "0", wrong: ["1", "255", "任意の番号"], explain: "各エリアはABRを介してエリア0（バックボーン）に接続する。" },
  { doc: "network/routing/igp.md", q: "OSPF で異なるエリア間のルーティングを仲介するルーターはどれか。", answer: "ABR（エリア境界ルーター）", wrong: ["DR（指名ルータ）", "BDR（副指名ルータ）", "ASBR（AS境界ルーター）"], explain: "ASBRはAS（自律システム）の境界で動くルーター。" },

  { doc: "network/routing/bgp.md", q: "2 Bytes のプライベートAS番号の範囲はどれか。", answer: "64,512〜65,535", wrong: ["1〜64,511", "65,536〜4,199,999,999", "4,200,000,000〜4,294,967,295"], explain: "4,200,000,000〜4,294,967,295 は 4 Bytes のプライベートAS番号。" },
  { doc: "network/routing/bgp.md", q: "AS番号 65500 は何に分類されるか。", answer: "プライベートAS番号（2 Bytes）", wrong: ["グローバルAS番号（2 Bytes）", "プライベートAS番号（4 Bytes）", "グローバルAS番号（4 Bytes）"], explain: "64,512〜65,535 の範囲なので2 Bytesのプライベート。実際に試験で問われた例がある。" },
  { doc: "network/routing/bgp.md", q: "BGP でループ検出に使われるパスアトリビュートはどれか。", answer: "AS_PATH", wrong: ["MED", "LOCAL_PREF", "NEXT_HOP"], explain: "AS_PATH に自AS番号が含まれていればループと判断して経路を破棄する。" },
  { doc: "network/routing/bgp.md", q: "同一AS内でのルートの優先度を表し、値が高いほど優先されるアトリビュートはどれか。", answer: "LOCAL_PREF", wrong: ["MED", "AS_PATH", "ORIGIN"], explain: "MED は他ASからのエクジットポイントの優先度で、低いほど優先。" },
  { doc: "network/routing/bgp.md", q: "AS_PATH に自AS番号を複数回追加し、経路を選ばれにくくする手法はどれか。", answer: "AS_PATHプリペンド", wrong: ["as-override", "allowas-in", "ルートリフレクタ"], explain: "AS_PATH を意図的に長くして他ASがそのルートを選ばないようにする。" },
  { doc: "network/routing/bgp.md", q: "受信した経路の AS_PATH に自AS番号が含まれていても、ループと判断せずに受け入れる設定はどれか。", answer: "allowas-in", wrong: ["as-override", "AS_PATHプリペンド", "ルートリフレクタ"], explain: "as-override は広報時にネイバーのAS番号を自AS番号に書き換える設定。" },
  { doc: "network/routing/bgp.md", q: "iBGP でフルメッシュ構成を不要にする仕組みはどれか。", answer: "ルートリフレクタ", wrong: ["AS_PATHプリペンド", "allowas-in", "ECMP"], explain: "iBGPピアから学習した経路を他のiBGPピアに反射する。複数ある場合はクラスターIDでループを防ぐ。" },
  { doc: "network/routing/bgp.md", q: "BGP セッションの生存確認のために定期的に送られるメッセージはどれか。", answer: "KEEPALIVE", wrong: ["OPEN", "UPDATE", "NOTIFICATION"], explain: "OPEN=セッション確立、UPDATE=ルート広告/更新、NOTIFICATION=エラー通知。" },
  { doc: "network/routing/bgp.md", q: "BGP が経路交換に使うポートはどれか。", answer: "TCP 179", wrong: ["UDP 179", "TCP 520", "UDP 520"], explain: "BGP は TCP 179 を使う。" },

  { doc: "network/routing/reliability.md", q: "ECMP の説明として正しいものはどれか。", answer: "同じコストの複数経路を同時に利用する", wrong: ["コストが最も低い単一の経路だけを利用する", "障害時にのみ予備経路へ切り替える", "経路ごとに異なる暗号化を行う"], explain: "通常のルーティングは最低コストの単一経路を選ぶが、ECMPは同コスト経路を同時に使う。" },
  { doc: "network/routing/reliability.md", q: "ECMP の負荷分散で、パケット順序の乱れを防げる方式はどれか。", answer: "ハッシュベース（フロー単位で経路を固定）", wrong: ["ラウンドロビン方式", "ランダム方式", "帯域比率方式"], explain: "ラウンドロビンは順序が入れ替わる可能性があり、TCP通信ではあまり使われない。" },
  { doc: "network/routing/reliability.md", q: "BFD の特徴として正しいものはどれか。", answer: "50ミリ秒などの短い間隔で死活監視し、高速に障害を検知する", wrong: ["経路情報を交換して最短経路を計算する", "30秒間隔で経路を更新する", "複数経路にトラフィックを分散する"], explain: "BFD はオーバヘッドが少なくなるようシンプルに設計された死活監視プロトコル。" },

  { doc: "network/routing/multicast.md", q: "全ホスト宛のマルチキャストアドレスはどれか。", answer: "224.0.0.1", wrong: ["224.0.0.2", "224.0.0.5", "239.0.0.1"], explain: "224.0.0.2 は全ルータ宛、224.0.0.5 は全OSPFルータ宛。" },
  { doc: "network/routing/multicast.md", q: "VRRP 用に予約されているマルチキャストアドレスはどれか。", answer: "224.0.0.18", wrong: ["224.0.0.22", "224.0.0.13", "224.0.0.6"], explain: "224.0.0.22=IGMP、224.0.0.13=PIM、224.0.0.6=全OSPF DR/BDR。" },
  { doc: "network/routing/multicast.md", q: "組織内などのプライベート空間で使用されるマルチキャストアドレスの範囲はどれか。", answer: "239.0.0.0〜239.255.255.255", wrong: ["224.0.0.0〜224.0.0.255", "224.0.1.0〜238.255.255.255", "240.0.0.0〜255.255.255.255"], explain: "224.0.0.0〜224.0.0.255 はリンクローカル、224.0.1.0〜238.255.255.255 はグローバル。" },
  { doc: "network/routing/multicast.md", q: "マルチキャストMACアドレスの先頭部分はどれか。", answer: "01-00-5E", wrong: ["01-80-C2", "FF-FF-FF", "00-00-5E"], explain: "先頭24bitが01-00-5E、25ビット目は常に0で固定。" },
  { doc: "network/routing/multicast.md", q: "224.100.1.1 と 224.228.1.1 が同じマルチキャストMACアドレスになる理由はどれか。", answer: "IPアドレスの下位23bitだけがMACアドレスにコピーされるため", wrong: ["上位8bitだけがMACアドレスにコピーされるため", "MACアドレスはランダムに割り当てられるため", "第2オクテットは常に0に変換されるため"], explain: "1:1にならない場合、受信端末はIPアドレスで自分宛てか判断する。" },
  { doc: "network/routing/multicast.md", q: "RP（Rendezvous Point）と join を用いて経路を決定する PIM のモードはどれか。", answer: "PIM-SM（スパースモード）", wrong: ["PIM-DM（デンスモード）", "PIM-SSM", "IGMPv3"], explain: "PIM-SMは受信端末が分散している環境(WAN)向け。PIM-DMはFlood & Prune方式。" },
  { doc: "network/routing/multicast.md", q: "PIM-DM の経路決定方式はどれか。", answer: "Flood & Prune", wrong: ["RP と join", "送信元指定", "Flood & Learn"], explain: "全ルーターにFloodし、不要なルーターをPruneする。受信端末が密集した環境向け。" },
  { doc: "network/routing/multicast.md", q: "IGMPv2 で追加された機能はどれか。", answer: "Leave Group による明示的な脱退", wrong: ["配信元を指定するソースフィルタ", "Membership Query による存在確認", "Membership Report による参加通知"], explain: "ソースフィルタはIGMPv3。Membership Query と Report はIGMPv1から存在する。" },
  { doc: "network/routing/multicast.md", q: "IGMPv2 で受信端末が Leave Group を送る宛先はどれか。", answer: "224.0.0.2（全ルーター）", wrong: ["224.0.0.1（全端末）", "224.0.0.22（IGMP）", "脱退するグループのアドレス"], explain: "ルーターは Specific Membership Query で他に受信端末がいるか確認する。" },
  { doc: "network/routing/multicast.md", q: "PIM-SSM を利用するために必要なものはどれか。", answer: "IGMPv3 のソースフィルタ機能", wrong: ["IGMPv2 の Leave Group", "RP（Rendezvous Point）", "Flood & Prune"], explain: "PIM-SSMは配信元IPアドレスを指定してディストリビューションツリーを構築する。" },
  { doc: "network/routing/multicast.md", q: "マルチキャストグループへの参加と脱退を管理するプロトコルはどれか。", answer: "IGMP", wrong: ["PIM", "LLDP", "RSVP"], explain: "PIM はマルチキャスト用のルーティングプロトコル。" },

  // ---- 冗長化・負荷分散 ----
  { doc: "network/redundancy/vrrp.md", q: "VRRP アドバタイズメントの送信先アドレスはどれか。", answer: "224.0.0.18", wrong: ["224.0.0.1", "224.0.0.5", "255.255.255.255"], explain: "VRRP はマルチキャストアドレス 224.0.0.18 を使う。" },
  { doc: "network/redundancy/vrrp.md", q: "VRRP の Master 選出方法として正しいものはどれか。", answer: "Priorityが最も大きいルーター。同じなら実IPアドレスが最も大きいルーター", wrong: ["Priorityが最も小さいルーター。同じならMACアドレスが最も小さいルーター", "最初に起動したルーター", "実IPアドレスが最も小さいルーター"], explain: "STPのルートブリッジ（最小が選ばれる）と混同しないこと。" },
  { doc: "network/redundancy/vrrp.md", q: "VRRP の Preempt 機能の説明として正しいものはどれか。", answer: "より Priority の高いルーターが現れたとき、そのルーターが Master になる", wrong: ["Master がダウンするまで再選出を行わない", "Backup ルーターが常に負荷分散する", "アドバタイズメントの送信間隔を短くする"], explain: "通常は現在の Master がダウンするまで再選出は行われない。" },
  { doc: "network/redundancy/vrrp.md", q: "VRRP のグループを示す ID はどれか。", answer: "VRID", wrong: ["VNI", "VID", "SPI"], explain: "VRID（Virtual Router ID）のグループ内で Master/Backup を選出する。" },

  { doc: "network/redundancy/load-balancer.md", q: "DSR（Direct Server Return）の説明として正しいものはどれか。", answer: "ワンアーム構成で、戻りの通信をLBを経由せず直接クライアントに返す", wrong: ["行きと戻りの通信を必ずLBで折り返す", "DNSで最も近いサーバーに振り分ける", "サーバーの代わりにSSL/TLS通信を終端する"], explain: "メリットはパフォーマンス向上、デメリットはSSL/TLSアクセラレータが使えないこと。" },
  { doc: "network/redundancy/load-balancer.md", q: "DSR 構成でバックエンドサーバーが Loopback に設定するものはどれか。", answer: "LBの持つIPアドレス（VIP）", wrong: ["クライアントのIPアドレス", "デフォルトゲートウェイのアドレス", "マルチキャストアドレス"], explain: "LBはNATをしないため、サーバーはVIPを自分宛てとして受信し、送信元VIPで直接応答する。" },
  { doc: "network/redundancy/load-balancer.md", q: "Webアプリケーションの稼働状況を最も正確に監視できる死活監視方式はどれか。", answer: "HTTP/HTTPSプローブ", wrong: ["ICMPプローブ", "TCP/UDPプローブ", "ARPプローブ"], explain: "ICMPやTCP/UDPでは、Pingに応答してもWebサーバーはダウンしている状態などを判断できない。" },
  { doc: "network/redundancy/load-balancer.md", q: "GSLB の一般的な実現方法はどれか。", answer: "DNSで送信元IPを基に最も近いエッジサーバーのIPアドレスを応答する", wrong: ["LBが戻りの通信を直接クライアントに返す", "Cookieのセッション IDで同じサーバーに振り分ける", "BGPで同コストの経路を分散する"], explain: "GSLB (Global Server Load Balancing) は DNS ベースが一般的。" },
  { doc: "network/redundancy/load-balancer.md", q: "セキュリティ上の懸念があるため、あまり一般的ではないセッション維持方式はどれか。", answer: "URLパラメーターベース", wrong: ["IPベース", "Cookieベース", "IPのハッシュ値ベース"], explain: "URLに session_id=123 のようなパラメーターを含める方式。" },
  { doc: "network/redundancy/load-balancer.md", q: "SSL/TLS アクセラレーター機能と併せて利用されることが多いセッション維持方式はどれか。", answer: "Cookieベース", wrong: ["IPベース", "URLパラメーターベース", "DNSベース"], explain: "SSL/TLSを終端するとHTTPS通信の中身（Cookie）を確認できるため。" },
  { doc: "network/redundancy/load-balancer.md", q: "ワンアーム構成の説明として正しいものはどれか。", answer: "LBに直接サーバーを接続せず、ネットワークを介して間接的に接続する", wrong: ["クライアントとサーバーの間にLBを直列に挟む", "LBを2台で冗長化する", "LBを使わずにDNSで負荷分散する"], explain: "LBの追加や交換がしやすく、スケーラビリティに優れる。" },

  // ---- 運用管理 ----
  { doc: "network/operation/qos.md", q: "入力トラフィックが基準値を超えた場合に超過分を破棄する方式はどれか。", answer: "ポリシング", wrong: ["シェーピング", "マーキング", "キューイング"], explain: "シェーピングは出力トラフィックが基準値を超えないよう出力間隔を調整する方式。" },
  { doc: "network/operation/qos.md", q: "シェーピングの説明として正しいものはどれか。", answer: "出力トラフィックが基準値を超えないよう、パケットの出力間隔を調整する", wrong: ["入力トラフィックの超過分を破棄する", "パケットに優先度を付与する", "特定の通信に帯域を予約する"], explain: "語源は shape（形作る）。なめらかに調整するというニュアンス。" },
  { doc: "network/operation/qos.md", q: "DSCP のビット数とクラス数の組み合わせはどれか。", answer: "6bit・64クラス", wrong: ["3bit・8クラス", "8bit・256クラス", "12bit・4096クラス"], explain: "CoS と IP Precedence は 3bit・8クラス（0〜7）。" },
  { doc: "network/operation/qos.md", q: "現在一般的で、大規模なネットワークに適した QoS の実現方法はどれか。", answer: "DiffServ", wrong: ["IntServ", "RSVP", "ポリシング"], explain: "IntServは厳密なQoSを適用できるがRSVP通信も流れるため大規模には向かない。" },
  { doc: "network/operation/qos.md", q: "IntServ で帯域の予約に使われるプロトコルはどれか。", answer: "RSVP", wrong: ["DSCP", "LLDP", "SIP"], explain: "RSVP (Resource Reservation Protocol) でネットワーク全体でリソースを予約する。" },
  { doc: "network/operation/qos.md", q: "L2 の優先度制御で CoS 値が格納されるフィールドはどれか。", answer: "IEEE 802.1Q VLANヘッダの PCP", wrong: ["IPヘッダの ToS", "VLANヘッダの TPID", "VLANヘッダの VID"], explain: "CoS はフレーム、DSCP はパケット（IPヘッダのToS）の優先度付けに使う。" },
  { doc: "network/operation/qos.md", q: "IP Precedence の説明として正しいものはどれか。", answer: "ToSフィールドの優先度ビット(3bit)のみを利用する方式", wrong: ["ToSフィールドの6bitを利用する方式", "VLANヘッダのPCPを利用する方式", "RSVPで帯域を予約する方式"], explain: "6bitを使うのはDSCP。" },
  { doc: "network/operation/qos.md", q: "DSCP 値の下位3bit（フラグビット）の値が大きいとどうなるか。", answer: "破棄確率が高くなる", wrong: ["優先度が高くなる", "帯域が予約される", "暗号化が有効になる"], explain: "上位3bit（優先度ビット）は値が大きいほど優先度が高い。" },

  { doc: "network/operation/monitoring.md", q: "SNMP の Trap（Agent → Manager）で使われるポートはどれか。", answer: "UDP 162", wrong: ["UDP 161", "UDP 514", "UDP 4739"], explain: "UDP 161 は Manager → Agent。514 は Syslog、4739 は IPFIX。" },
  { doc: "network/operation/monitoring.md", q: "Syslog が一般的に使うポートはどれか。", answer: "UDP 514", wrong: ["UDP 162", "TCP 443", "UDP 123"], explain: "監視対象の機器は Syslog サーバ宛に UDP 514 でログを転送する。" },
  { doc: "network/operation/monitoring.md", q: "Trap に確認応答の仕組みを設け、応答がなければ再送する SNMP メッセージはどれか。", answer: "Inform-Request", wrong: ["Trap", "Get-Bulk-Request", "Set-Request"], explain: "Inform-Request は SNMPv2c から。" },
  { doc: "network/operation/monitoring.md", q: "SNMPv3 の特徴として正しいものはどれか。", answer: "コミュニティではなくユーザー単位の認証・暗号化ができる", wrong: ["SNMPコミュニティによる平文認証を行う", "Trapをサポートしない", "Get-Bulk-Requestをサポートしない"], explain: "v1 と v2c はコミュニティによる平文認証。v3 はユーザー単位でアクセス可能なMIBも制限できる。" },
  { doc: "network/operation/monitoring.md", q: "LLDP を標準化した規格はどれか。", answer: "IEEE 802.1ab", wrong: ["IEEE 802.1Q", "IEEE 802.1X", "IEEE 802.1w"], explain: "LLDP は隣接機器に自身の機器情報を通知するL2プロトコル。" },
  { doc: "network/operation/monitoring.md", q: "SNMP で MIB の各情報を識別するものはどれか。", answer: "OID（Object ID）", wrong: ["VNI", "SPI", "FEC"], explain: "例: ifSpeed = 1.3.6.1.2.1.2.2.1.5。" },
  { doc: "network/operation/monitoring.md", q: "複数の OID の情報を一度に要求する SNMP メッセージはどれか。", answer: "Get-Bulk-Request", wrong: ["Get-Next-Request", "Get-Request", "Inform-Request"], explain: "Get-Next-Request を改良したもので、SNMPv2c から。" },
  { doc: "network/operation/monitoring.md", q: "ネットワークを流れるフロー（IP・プロトコル・ポートの組み合わせ）を監視・分析するプロトコルはどれか。", answer: "NetFlow / IPFIX", wrong: ["SNMP", "Syslog", "LLDP"], explain: "SNMPとSyslogは機器の監視に特化、NetFlow/IPFIXはフローの監視や分析に特化。" },

  // ---- プロトコル ----
  { doc: "network/protocol/tcp.md", q: "TCP でコネクションの開始を示すフラグはどれか。", answer: "SYN", wrong: ["FIN", "RST", "PSH"], explain: "FIN=終了、RST=強制終了、PSH=バッファリングを抑制して迅速に上位へ渡す。" },
  { doc: "network/protocol/tcp.md", q: "TCP でコネクションの強制終了を示すフラグはどれか。", answer: "RST", wrong: ["FIN", "URG", "ECE"], explain: "通常の終了は FIN。" },
  { doc: "network/protocol/tcp.md", q: "シーケンス番号 100 で 1200 Byte のデータを受け取った。受信側が返す確認応答(ACK)番号はどれか。", answer: "1300", wrong: ["1200", "101", "1301"], explain: "ACK番号 = 受け取ったシーケンス番号 + 受け取ったデータサイズ。" },
  { doc: "network/protocol/tcp.md", q: "受信側が Window=0 を通知した後、送信側が最新のウィンドウサイズを要求するものはどれか。", answer: "ウィンドウプローブ", wrong: ["ウィンドウアップデート", "スライディングウィンドウ", "再送制御"], explain: "受信側はウィンドウアップデートで最新のウィンドウサイズを通知する。" },
  { doc: "network/protocol/tcp.md", q: "受信側が自身の負荷状況に応じてウィンドウサイズを変更する仕組みはどれか。", answer: "フロー制御", wrong: ["順序制御", "再送制御", "輻輳回避"], explain: "TCPヘッダのウィンドウサイズを変更して通知することで実現する。" },
  { doc: "network/protocol/tcp.md", q: "RFC 9293 でフラグフィールドに追加されたものはどれか。", answer: "CWR と ECE", wrong: ["URG と PSH", "SYN と FIN", "ACK と RST"], explain: "RFC 793 は 6bit（URG, ACK, PSH, RST, SYN, FIN）、RFC 9293 は 8bit。" },
  { doc: "network/protocol/tcp.md", q: "TCP の CWR フラグの意味はどれか。", answer: "輻輳ウィンドウを減少させたことを通知する", wrong: ["輻輳の発生を通知する", "緊急ポインタが有効であることを示す", "コネクションを強制終了する"], explain: "輻輳の発生を通知するのは ECE。" },
  { doc: "network/protocol/tcp.md", q: "Ackを待たずにまとめて送ったデータの一部にAckが返った時点で、次のデータを送る仕組みはどれか。", answer: "スライディングウィンドウ", wrong: ["フロー制御", "再送制御", "順序制御"], explain: "Ackが得られた分のウィンドウは空いたと判断して次を送る。" },

  { doc: "network/protocol/udp.md", q: "UDP ヘッダのサイズはどれか。", answer: "8 Byte（固定）", wrong: ["20 Byte（可変）", "4 Byte（固定）", "40 Byte（固定）"], explain: "UDPは可変長オプションを持たない8 Byteの固定ヘッダ。" },
  { doc: "network/protocol/udp.md", q: "UDP ヘッダに含まれないフィールドはどれか。", answer: "シーケンス番号", wrong: ["Length", "Checksum", "Destination Port"], explain: "UDP は順序保証やコネクション管理の仕組みを持たない。" },
  { doc: "network/protocol/udp.md", q: "UDP ヘッダの Length が示すものはどれか。", answer: "UDPヘッダ＋データのサイズ", wrong: ["データ部分のみのサイズ", "IPパケット全体のサイズ", "ヘッダのみのサイズ"], explain: "Length はヘッダとデータを合わせたサイズ。" },

  { doc: "network/protocol/well-known-ports.md", q: "SMTP のサブミッションポート（STARTTLS）はどれか。", answer: "587", wrong: ["25", "143", "110"], explain: "25 は SMTP、143 は IMAP、110 は POP3。" },
  { doc: "network/protocol/well-known-ports.md", q: "IMAPS のポート番号はどれか。", answer: "993", wrong: ["995", "143", "443"], explain: "995 は POP3S、143 は IMAP。" },
  { doc: "network/protocol/well-known-ports.md", q: "NTP が使うポートはどれか。", answer: "UDP 123", wrong: ["TCP 123", "UDP 161", "UDP 514"], explain: "161 は SNMP、514 は Syslog。" },
  { doc: "network/protocol/well-known-ports.md", q: "SMB が使うポート番号はどれか。", answer: "445", wrong: ["443", "3389", "22"], explain: "443 は HTTPS、22 は SSH。" },
  { doc: "network/protocol/well-known-ports.md", q: "FTP のコントロール（制御）用ポートはどれか。", answer: "21", wrong: ["20", "22", "23"], explain: "20 は FTP のデータ転送、22 は SSH、23 は Telnet。" },
  { doc: "network/protocol/well-known-ports.md", q: "DNS が使うポートとして正しいものはどれか。", answer: "TCP/UDP 53", wrong: ["UDP 67", "TCP 25", "UDP 123"], explain: "67 は DHCPサーバ、25 は SMTP、123 は NTP。" },

  { doc: "network/protocol/dhcp.md", q: "DHCP Discover メッセージの送信方法はどれか。", answer: "ブロードキャスト", wrong: ["ユニキャスト", "224.0.0.1 宛のマルチキャスト", "エニーキャスト"], explain: "クライアントはDHCPサーバーを探すためにブロードキャストする。" },
  { doc: "network/protocol/dhcp.md", q: "DHCP のメッセージの流れとして正しい順番はどれか。", answer: "Discover → Offer → Request → ACK", wrong: ["Request → Offer → Discover → ACK", "Discover → Request → Offer → ACK", "Offer → Discover → ACK → Request"], explain: "探す(Discover) → 提案(Offer) → 要求(Request) → 確認(ACK)。" },
  { doc: "network/protocol/dhcp.md", q: "DHCP のサーバー側とクライアント側のポート番号の組み合わせはどれか。", answer: "サーバー 67 / クライアント 68（UDP）", wrong: ["サーバー 68 / クライアント 67（UDP）", "サーバー 67 / クライアント 68（TCP）", "サーバー 53 / クライアント 67（UDP）"], explain: "DHCP は L7 のプロトコルだが、トランスポートには UDP を使う。" },
  { doc: "network/protocol/dhcp.md", q: "DHCP のリース期間が終了するとクライアントはどうするか。", answer: "DHCPサーバーにIPアドレスの更新を要求する", wrong: ["IPアドレスを自動的に固定化する", "別のサーバーにDiscoverを送り直すしかない", "即座に通信を停止する"], explain: "割り当てたIPアドレスはリース期間だけ提供される。" },

  { doc: "network/protocol/http.md", q: "HTTP ステータスコード 403 の意味はどれか。", answer: "クライアントの権限が不足している", wrong: ["認証情報が無効である", "リソースが存在しない", "リクエスト内容が無効である"], explain: "401 は認証情報が無効、404 はリソースが存在しない、400 はリクエストが無効。" },
  { doc: "network/protocol/http.md", q: "HTTP ステータスコード 429 の意味はどれか。", answer: "短期間にリクエストを送りすぎてレートリミットを超えている", wrong: ["サーバー内部で予期せぬエラーが起きた", "恒久的に別のページへリダイレクトする", "ゲートウェイがサーバーから無効な応答を受けた"], explain: "APIなどでリクエスト数の制限がある場合に返される。" },
  { doc: "network/protocol/http.md", q: "経路中のプロキシがサーバーから無効なレスポンスを受信したことを示すステータスコードはどれか。", answer: "502 Bad Gateway", wrong: ["500 Internal Server Error", "404 Not Found", "302 Found"], explain: "500 はサーバー内部のエラー。" },
  { doc: "network/protocol/http.md", q: "プロキシを経由したとき、リクエスト元の送信元IPアドレスをWebサーバーに伝えるヘッダはどれか。", answer: "X-Forwarded-For", wrong: ["X-Forwarded-Host", "X-Forwarded-Proto", "Referer"], explain: "Host は宛先ホスト、Proto はプロトコル(HTTP/HTTPS)。標準仕様としては Forwarded ヘッダもある。" },
  { doc: "network/protocol/http.md", q: "HTTPS 通信の場合にのみ Cookie を送信するよう指示する Set-Cookie の属性はどれか。", answer: "Secure", wrong: ["Expires", "Domain", "Path"], explain: "平文でセッションIDをやり取りするのは危険なため Secure 属性が必要。" },
  { doc: "network/protocol/http.md", q: "Digest 認証の説明として正しいものはどれか。", answer: "ユーザー名+パスワード+ランダム文字列をハッシュ化して送信する", wrong: ["ユーザー名+パスワードをBase64でエンコードして送信する", "証明書を提示して認証する", "ワンタイムパスワードをSMSで送る"], explain: "Base64で送るのは Basic 認証で、盗聴されると認証情報を復元できる。" },
  { doc: "network/protocol/http.md", q: "HTTP/3 が採用しているトランスポートプロトコルはどれか。", answer: "QUIC（UDPベース）", wrong: ["TCP", "SCTP", "RTP"], explain: "QUICは1ラウンドトリップで接続確立と暗号化を同時に行える。" },
  { doc: "network/protocol/http.md", q: "プロキシがクライアントに認証を要求するときに使うヘッダはどれか。", answer: "Proxy-Authenticate", wrong: ["Proxy-Authorization", "WWW-Authenticate", "Authorization"], explain: "クライアントは Proxy-Authorization で認証情報を返す。Webサーバーの場合は WWW-Authenticate / Authorization。" },
  { doc: "network/protocol/http.md", q: "恒久的に別のページへリダイレクトすることを示すステータスコードはどれか。", answer: "301 Moved Permanently", wrong: ["302 Found", "200 OK", "100 Continue"], explain: "302 は一時的なリダイレクト。" },
  { doc: "network/protocol/http.md", q: "1つのTCPコネクション上で複数のリクエスト/レスポンスをストリームとして扱い、バイナリでやり取りするHTTPのバージョンはどれか。", answer: "HTTP/2", wrong: ["HTTP/1.1", "HTTP/1.0", "HTTP/3"], explain: "HTTP/2 はヘッダ圧縮(HPACK)やサーバープッシュも備える。HTTP/3 は QUIC を使う。" },

  { doc: "network/protocol/tls.md", q: "TLS 1.3 で廃止された鍵交換方式はどれか。", answer: "RSA鍵交換", wrong: ["DHE", "ECDHE", "PSK"], explain: "TLS 1.3 では (EC)DHE を使い、前方秘匿性を確保する。" },
  { doc: "network/protocol/tls.md", q: "前方秘匿性の説明として正しいものはどれか。", answer: "セッション終了後に過去の通信内容を復号することが困難である", wrong: ["通信前に相手の身元を確認できる", "改ざんを検知できる", "鍵を事前に共有しておく必要がない"], explain: "TLS 1.3 は (EC)DHE で公開鍵による暗号化なしに共通鍵を生成するため前方秘匿性がある。" },
  { doc: "network/protocol/tls.md", q: "TLS 1.2 で共通鍵のもとになる情報（プリマスターシークレット）を送るメッセージはどれか。", answer: "Client Key Exchange", wrong: ["Client Hello", "Server Key Exchange", "Change Cipher Spec"], explain: "Change Cipher Spec はそれ以降共通鍵で暗号化することを通知するメッセージ。" },
  { doc: "network/protocol/tls.md", q: "TLS 1.3 で Client Hello / Server Hello に含まれる、共通鍵のもとになる情報はどれか。", answer: "key_share", wrong: ["Session ID", "Finished", "Certificate Request"], explain: "最初の1往復で key_share を交換し、ネゴシエーション中から暗号化できる。" },
  { doc: "network/protocol/tls.md", q: "TLS 1.3 で HTTP のやり取りが始まるのは何往復目からか。", answer: "2往復目", wrong: ["1往復目", "3往復目", "4往復目"], explain: "TLS 1.2 は3往復目から暗号化通信を開始する。" },
  { doc: "network/protocol/tls.md", q: "暗号化と同時に認証も行う「認証付き暗号」の略称はどれか。", answer: "AEAD", wrong: ["HMAC", "ECDHE", "PSK"], explain: "AEAD = Authenticated Encryption with Associated Data。" },

  { doc: "network/protocol/email-header.md", q: "メール配送に失敗した場合のエラーメールの送信先を示すヘッダはどれか。", answer: "Return-Path", wrong: ["Reply-To", "From", "Received"], explain: "Reply-To は返信先アドレス。" },
  { doc: "network/protocol/email-header.md", q: "Received ヘッダを使ってメールの転送経路をたどるときの読み方はどれか。", answer: "下から上にたどる（上が新しい）", wrong: ["上から下にたどる（上が古い）", "From ヘッダの順にたどる", "時刻の新しい順に並べ替える必要がある"], explain: "経路上のサーバが先頭に追加していくため、上が新しい。" },
  { doc: "network/protocol/email-header.md", q: "電子メールのヘッダについて正しいものはどれか。", answer: "ヘッダは偽装することができる", wrong: ["ヘッダは暗号化されているため偽装できない", "Received ヘッダは送信者しか追加できない", "From ヘッダは受信サーバが必ず検証する"], explain: "偽装への対策として SPF / DKIM / DMARC などの送信ドメイン認証がある。" },
  { doc: "network/protocol/email-header.md", q: "メールを作成したメールクライアントを示すヘッダはどれか。", answer: "X-Mailer", wrong: ["Message-ID", "Content-Type", "MIME-Version"], explain: "Message-ID はメールの一意な識別子。" },

  { doc: "network/protocol/mail-security.md", q: "SPF レコードを記述する DNS レコードの種類はどれか。", answer: "TXT", wrong: ["MX", "A", "PTR"], explain: "SPF・DKIM・DMARC はいずれも TXT レコードに記述する。" },
  { doc: "network/protocol/mail-security.md", q: "SPF の「~all」の意味はどれか。", answer: "許可以外の送信元をソフトフェイルとして扱う", wrong: ["許可以外の送信元を認証失敗として扱う", "すべての送信元を許可する", "SPFの検証を行わない"], explain: "「-all」は認証失敗として扱い、通常は拒否される。" },
  { doc: "network/protocol/mail-security.md", q: "DKIM の説明として正しいものはどれか。", answer: "送信者がデジタル署名を付け、受信側がDNSの公開鍵で検証する", wrong: ["送信を許可するメールサーバのIPアドレスをDNSに登録する", "SPFとDKIMの結果に基づく処理ポリシーを示す", "メールを暗号化して送信する"], explain: "IPアドレスを登録するのは SPF、処理ポリシーを示すのは DMARC。" },
  { doc: "network/protocol/mail-security.md", q: "SPF と DKIM の結果に基づいて受信後の処理方法を指定する仕組みはどれか。", answer: "DMARC", wrong: ["SPF", "DKIM", "STARTTLS"], explain: "ポリシーは none / quarantine / reject。" },
  { doc: "network/protocol/mail-security.md", q: "DMARC ポリシーで「p=quarantine」を指定した場合の処理はどれか。", answer: "迷惑メールフォルダに移動する", wrong: ["メールを拒否する", "何もしない", "送信者に再送を要求する"], explain: "reject は拒否、none は DMARC を適用しない。" },
  { doc: "network/protocol/mail-security.md", q: "DMARC レコードでアグリゲートレポートの送信先を指定する項目はどれか。", answer: "rua", wrong: ["ruf", "fo", "p"], explain: "ruf はフォレンジックレポートの送信先。" },

  { doc: "network/protocol/voip.md", q: "電話機間の接続（呼び出しや切断）を行う呼制御のプロトコルはどれか。", answer: "SIP", wrong: ["RTP", "RTCP", "SDP"], explain: "SIPで呼制御（シグナリング）、RTPで音声を転送する。" },
  { doc: "network/protocol/voip.md", q: "音声や動画などリアルタイム性が必要なデータを転送するプロトコルはどれか。", answer: "RTP", wrong: ["SIP", "SDP", "RSVP"], explain: "RTP は UDP 上で動作し、ジッターやパケットロスを最小化するよう設計されている。" },
  { doc: "network/protocol/voip.md", q: "パケットロスやジッターなどの付加情報をやり取りし、受信側のフィードバックを送信側に提供するプロトコルはどれか。", answer: "RTCP", wrong: ["RTP", "SIP", "SNMP"], explain: "RTCP (Real-time Transport Control Protocol)。" },
  { doc: "network/protocol/voip.md", q: "SIP で音声/動画・セッション名・使用するポート番号などのメディア情報を記述する形式はどれか。", answer: "SDP", wrong: ["RTP", "RTCP", "MIB"], explain: "SDP で双方のメディア設定を統一する。" },
  { doc: "network/protocol/voip.md", q: "SIP で接続開始をリクエストするメッセージはどれか。", answer: "INVITE", wrong: ["REGISTER", "ACK", "BYE"], explain: "REGISTER=自身の情報を登録、ACK=接続の確立を通知、BYE=接続の終了を通知。" },
  { doc: "network/protocol/voip.md", q: "4kHz のアナログ信号を忠実に再現するために必要なサンプリング周波数はどれか。", answer: "8kHz", wrong: ["4kHz", "2kHz", "44.1kHz"], explain: "標本化定理により、周期の2倍以上でサンプリングする必要がある。" },
  { doc: "network/protocol/voip.md", q: "VoIP で PCM を使った場合に消費する帯域幅はどれくらいか。", answer: "64 kbps 程度", wrong: ["8 kbps 程度", "1.5 Mbps 程度", "16 kbps 程度"], explain: "CS-ACELP は 8 kbps 程度だが、PCMより音質が劣る。" },
  { doc: "network/protocol/voip.md", q: "ジッターの説明として正しいものはどれか。", answer: "パケットの到着時間のばらつき", wrong: ["パケットが失われる割合", "往復にかかる時間", "音声を数値に変換する工程"], explain: "RTP はジッターを最小化するよう設計されている。" },
  { doc: "network/protocol/voip.md", q: "サンプリングした値を離散的な数値に変換する工程はどれか。", answer: "量子化", wrong: ["標本化", "符号化", "圧縮"], explain: "標本化 → 量子化 → 符号化 の順で音声をデジタルデータに変換する。" },
];
