// 過去問の単語帳（「過去問の単語帳」画面で表示する）。
// ネットワークスペシャリスト試験（令和5〜7年度 春期）の午前Ⅱ・午後Ⅰ・午後Ⅱに出てきた重要語を拾い，
// 説明は本サイトで作成したもの（問題文の転載ではない）。
// field: 分野のキー（TANGO_FIELDS），src: [[令和の年度, "区分 問番号"], ...]
window.TANGO_FIELDS = {
  lan: "LAN・無線",
  ip: "IP・ルーティング",
  wan: "WAN・VPN",
  red: "冗長化・負荷分散",
  app: "プロトコル・アプリ",
  sec: "セキュリティ",
  etc: "IT基礎",
};

window.TANGO = [
  // ---- LAN・無線 ----
  { field: "lan", term: "イーサネットのヘッダ＋FCS", desc: "宛先MAC6＋送信元MAC6＋タイプ2＋FCS4＝18オクテット", src: [[7, "午前Ⅱ 問2"]] },
  { field: "lan", term: "10GBASE-T のケーブル長", desc: "カテゴリ6Aで最大100m（カテゴリ6は55m）", src: [[7, "午前Ⅱ 問4"]] },
  { field: "lan", term: "802.11n / 802.11ac", desc: "11nは2.4GHz帯と5GHz帯，11acは5GHz帯のみ", src: [[7, "午前Ⅱ 問15"], [5, "午前Ⅱ 問15"]] },
  { field: "lan", term: "OFDM", desc: "データを直交する複数のサブキャリアに分けて送る多重化方式", src: [[5, "午前Ⅱ 問2"]] },
  { field: "lan", term: "トライバンド", desc: "2.4GHz帯と5GHz帯2つ（W52/W53・W56）を同時に使うAP", src: [[5, "午後Ⅰ 問3"]] },
  { field: "lan", term: "DFS", desc: "W53・W56でレーダーを検知すると別チャネルへ移る機能。通信断が起きる", src: [[5, "午後Ⅰ 問3"]] },
  { field: "lan", term: "チャネルボンディング", desc: "20MHz幅のチャネルを束ねて40MHz幅などにし高速化する", src: [[5, "午後Ⅰ 問3"]] },
  { field: "lan", term: "MU-MIMO / OFDMA", desc: "複数端末と同時に通信 / サブキャリアを複数端末で共有", src: [[5, "午後Ⅰ 問3"]] },
  { field: "lan", term: "SAE（WPA3）", desc: "PSKに代わる鍵交換。パスワードの辞書攻撃に強い", src: [[5, "午後Ⅰ 問3"]] },
  { field: "lan", term: "PoE+ / PoE++", desc: "IEEE 802.3at（最大30W）/ IEEE 802.3bt", src: [[5, "午後Ⅰ 問3"], [7, "午後Ⅰ 問2"]] },
  { field: "lan", term: "マルチギガビットイーサネット", desc: "2.5GBASE-T / 5GBASE-T", src: [[5, "午後Ⅰ 問3"]] },
  { field: "lan", term: "スタック接続", desc: "複数のスイッチを論理的に1台として扱う。筐体をまたいだLAGが組める", src: [[5, "午後Ⅰ 問3"]] },
  { field: "lan", term: "ブロードキャストストーム", desc: "ループになる誤接続でブロードキャストが増殖し続ける現象", src: [[5, "午後Ⅰ 問3"]] },
  { field: "lan", term: "MSTP", desc: "複数VLANをまとめたインスタンス単位でスパニングツリーを作る", src: [[5, "午前Ⅱ 問10"]] },
  { field: "lan", term: "802.1Q タグの位置", desc: "送信元MACアドレスとタイプ/長さの間に挿入される", src: [[5, "午前Ⅱ 問11"]] },
  { field: "lan", term: "IGMPスヌーピング", desc: "L2SWがJoin/Leaveを見て，必要なポートだけにマルチキャストを流す", src: [[5, "午後Ⅰ 問2"]] },
  { field: "lan", term: "VXLAN の VNI", desc: "24bit・約1,677万のL2ネットワークをL3上に作れる", src: [[6, "午後Ⅱ 問1"]] },
  { field: "lan", term: "VTEP にループバック", desc: "物理IFが1つ故障してもVTEPとして動き続けられる", src: [[6, "午後Ⅱ 問1"]] },
  { field: "lan", term: "EVPN", desc: "MP-BGPでVTEPとMACの対応を学習。フラッディングを減らす", src: [[6, "午後Ⅱ 問1"]] },
  { field: "lan", term: "ESI", desc: "同じサーバにつながる2台のL3SWのLAGに付ける共通の識別子", src: [[6, "午後Ⅱ 問1"]] },
  { field: "lan", term: "LPWA", desc: "低消費電力・広域の無線。LoRaWAN，Sigfox，LTE-M，NB-IoT", src: [[7, "午後Ⅱ 問2"]] },
  { field: "lan", term: "ISMバンド", desc: "免許不要の周波数帯。920MHz帯は2.4GHz帯より干渉が少ない", src: [[7, "午後Ⅱ 問2"]] },
  { field: "lan", term: "ローカル5G", desc: "土地・建物の所有者が免許を取得して構築できる5G", src: [[5, "午前Ⅱ 問14"]] },
  { field: "lan", term: "BUMフレーム", desc: "Broadcast・Unknown Unicast・Multicast。フラッディングされる", src: [[6, "午後Ⅱ 問1"]] },
  { field: "lan", term: "W52 / W53 / W56", desc: "5GHz帯のチャネル群。W53・W56はレーダー回避（DFS）が必要", src: [[5, "午後Ⅰ 問3"]] },
  { field: "lan", term: "WLC（無線LANコントローラ）", desc: "多数のAPを集中管理。死活監視・利用者認証・接続監視を行う", src: [[5, "午後Ⅰ 問3"]] },
  { field: "lan", term: "リンクアグリゲーション", desc: "複数リンクを束ねて1本として使う。平常時も全帯域を使える", src: [[5, "午後Ⅰ 問3"], [6, "午後Ⅱ 問1"]] },
  { field: "lan", term: "SIM カード", desc: "通信事業者が契約者を識別する情報を記録したカード", src: [[7, "午後Ⅱ 問2"]] },
  { field: "lan", term: "3GPP", desc: "LTE-M・NB-IoTなど移動通信の技術仕様を作る標準化プロジェクト", src: [[7, "午後Ⅱ 問2"]] },

  // ---- IP・ルーティング ----
  { field: "ip", term: "可変長サブネットマスク", desc: "セグメントごとに長さの違うサブネットマスクを使う", src: [[7, "午前Ⅱ 問8"]] },
  { field: "ip", term: "CIDR による集約", desc: "192.168.32.0〜35.0/24 → 192.168.32.0/22", src: [[6, "午前Ⅱ 問12"], [5, "午前Ⅱ 問12"]] },
  { field: "ip", term: "ホスト部の求め方", desc: "IPアドレス a と マスクの反転 の論理積（a & 〜m）", src: [[6, "午前Ⅱ 問11"]] },
  { field: "ip", term: "IPのプロトコル番号", desc: "ICMP=1，TCP=6，UDP=17，ESP=50，AH=51", src: [[7, "午前Ⅱ 問7"]] },
  { field: "ip", term: "IPv4 マルチキャスト", desc: "先頭4ビットが1110。残り28ビットでグループを識別", src: [[6, "午前Ⅱ 問7"]] },
  { field: "ip", term: "RIP", desc: "経路情報の交換にUDP（520番）を使う距離ベクトル型", src: [[7, "午前Ⅱ 問10"]] },
  { field: "ip", term: "OSPF", desc: "エリアをもつリンクステート型。LSDBを使う。IPv6はOSPFv3", src: [[6, "午前Ⅱ 問4"], [5, "午前Ⅱ 問3"]] },
  { field: "ip", term: "バックボーンエリア", desc: "OSPFのエリアID 0.0.0.0。他のエリアはここにつなぐ", src: [[7, "午後Ⅰ 問1"]] },
  { field: "ip", term: "OSPF のルータID", desc: "OSPFルータの識別子。ループバックアドレスを使うことが多い", src: [[7, "午後Ⅰ 問1"], [6, "午後Ⅱ 問1"]] },
  { field: "ip", term: "OSPF ネイバー認証", desc: "不正なOSPFルータとの経路交換を防ぐ", src: [[7, "午後Ⅰ 問1"]] },
  { field: "ip", term: "OSPF コストを最大に", desc: "作業前にそのルータを迂回させ，通信を止めずに保守する", src: [[7, "午後Ⅰ 問1"]] },
  { field: "ip", term: "経路の再配布", desc: "別のルーティングプロトコルへ経路を渡す。フィルタでループ防止", src: [[6, "午後Ⅰ 問2"]] },
  { field: "ip", term: "LSA Type5", desc: "外部から再配布した経路をASBRが広告する外部LSA", src: [[6, "午後Ⅰ 問2"]] },
  { field: "ip", term: "BGP-4", desc: "AS間の経路制御。経路が変わったときは差分だけ送る", src: [[6, "午前Ⅱ 問1"], [5, "午前Ⅱ 問7"]] },
  { field: "ip", term: "BGP の KEEPALIVE", desc: "一定時間届かないとBGP接続を切り，経路をクリアする", src: [[5, "午後Ⅱ 問1"]] },
  { field: "ip", term: "LOCAL_PREF / MED", desc: "LOCAL_PREFは大きいほど，MEDは小さいほど優先", src: [[6, "午後Ⅰ 問1"], [5, "午後Ⅱ 問1"]] },
  { field: "ip", term: "AS_PATH プリペンド", desc: "自AS番号を重ねて経路を選ばれにくくする（予備回線側）", src: [[7, "午後Ⅰ 問1"]] },
  { field: "ip", term: "next-hop-self", desc: "iBGPで広告する経路のネクストホップを自分のアドレスにする", src: [[5, "午後Ⅱ 問1"]] },
  { field: "ip", term: "as-override", desc: "AS_PATH中の相手AS番号を自AS番号に置き換えて広告する", src: [[6, "午後Ⅰ 問2"]] },
  { field: "ip", term: "プライベートAS番号", desc: "インターネットで使わないAS用。2オクテットでは64512〜65534", src: [[6, "午後Ⅰ 問2"]] },
  { field: "ip", term: "ルートリフレクタ", desc: "iBGPのフルメッシュを不要にする。冗長化はクラスターIDで", src: [[6, "午後Ⅱ 問1"]] },
  { field: "ip", term: "BGP の MD5 認証", desc: "共通パスワードで不正なBGP接続を防ぐ", src: [[6, "午後Ⅰ 問1"]] },
  { field: "ip", term: "RTBH", desc: "DDoSの宛先への経路をBGPで配り，攻撃元に近い所で捨てる", src: [[6, "午後Ⅰ 問1"]] },
  { field: "ip", term: "BGP Flowspec", desc: "送信元IPやポートなどの条件をBGPで配り，細かく攻撃を捨てる", src: [[6, "午後Ⅰ 問1"]] },
  { field: "ip", term: "ロンゲストマッチ", desc: "一致する経路のうちプレフィックスが最も長いものを選ぶ", src: [[7, "午後Ⅱ 問1"]] },
  { field: "ip", term: "Null 経路", desc: "未使用アドレス宛てを捨てる経路。ないとルータ間でループする", src: [[7, "午後Ⅱ 問1"]] },
  { field: "ip", term: "静的経路と BGP", desc: "同じ宛先なら静的経路が優先される", src: [[5, "午後Ⅱ 問1"]] },
  { field: "ip", term: "ポリシーベースルーティング", desc: "送信元IPなどの条件でネクストホップを決める", src: [[5, "午後Ⅱ 問1"], [6, "午後Ⅰ 問2"]] },
  { field: "ip", term: "リンクローカルアドレス", desc: "fe80::/64。同じリンク内でだけ有効なIPv6アドレス", src: [[7, "午後Ⅱ 問1"]] },
  { field: "ip", term: "Modified EUI-64", desc: "48bitのMACアドレスから64bitのインタフェースIDを作る", src: [[7, "午後Ⅱ 問1"]] },
  { field: "ip", term: "重複アドレス検出（DAD）", desc: "NSを送りNAが返らないことで重複がないか確認する", src: [[7, "午後Ⅱ 問1"], [7, "午前Ⅱ 問12"]] },
  { field: "ip", term: "ICMPv6 の近隣探索", desc: "IPv4のARPにあたるMACアドレス解決をIPv6で行う", src: [[6, "午前Ⅱ 問6"], [5, "午前Ⅱ 問1"]] },
  { field: "ip", term: "SLAAC", desc: "ルータのRAのプレフィックスからアドレスを自動生成する", src: [[7, "午後Ⅱ 問1"]] },
  { field: "ip", term: "PMTUD", desc: "経路上の最小MTUを検出。IPv6ではPacket Too Bigが返る", src: [[7, "午後Ⅱ 問1"]] },
  { field: "ip", term: "IPv4 へのフォールバック", desc: "IPv6が不通でもIPv4で表示され，障害に気付きにくい", src: [[7, "午後Ⅱ 問1"]] },
  { field: "ip", term: "PIM-SM / SSM", desc: "RPを使うマルチキャスト経路制御 / 送信元を指定する方式", src: [[5, "午後Ⅰ 問2"]] },
  { field: "ip", term: "IGMPv3", desc: "送信元とグループを指定して参加。グループアドレスの設計が楽", src: [[5, "午後Ⅰ 問2"]] },
  { field: "ip", term: "ユニキャスト配信の欠点", desc: "受信者の数に応じて送信元の通信量が増える", src: [[5, "午後Ⅰ 問2"]] },
  { field: "ip", term: "OpenFlow の Packet-In", desc: "スイッチが受信パケットをコントローラーへ送るメッセージ", src: [[7, "午前Ⅱ 問13"]] },
  { field: "ip", term: "ECMP", desc: "コスト合計が等しい複数の経路で負荷分散する", src: [[6, "午後Ⅱ 問1"]] },
  { field: "ip", term: "ディストリビューションツリー", desc: "PIMのJoinで作られるマルチキャストの配信経路", src: [[5, "午後Ⅰ 問2"]] },
  { field: "ip", term: "IPv6 アドレスの表記", desc: "128ビットを16ビットずつ“:”で区切る", src: [[7, "午後Ⅱ 問1"]] },
  { field: "ip", term: "GUA", desc: "グローバルユニキャストアドレス。インターネットで一意なIPv6アドレス", src: [[7, "午後Ⅱ 問1"]] },
  { field: "ip", term: "RS / RA", desc: "ルータを探す要求 / ルータがプレフィックスなどを知らせる広告", src: [[7, "午後Ⅱ 問1"]] },
  { field: "ip", term: "NS / NA", desc: "近隣要請 / 近隣広告。IPv6のアドレス解決や重複検出に使う", src: [[7, "午後Ⅱ 問1"]] },
  { field: "ip", term: "ホップリミット", desc: "IPv6版のTTL。ルータを通るたびに1減り，0で破棄される", src: [[7, "午後Ⅱ 問1"]] },
  { field: "ip", term: "traceroute6", desc: "IPv6で経由するルータを調べるコマンド。GUAがあると識別しやすい", src: [[7, "午後Ⅱ 問1"]] },
  { field: "ip", term: "OSPFv3", desc: "IPv6対応のOSPF。リンクローカルアドレスで隣接関係を作る", src: [[6, "午前Ⅱ 問14"], [7, "午後Ⅱ 問1"]] },
  { field: "ip", term: "iBGP / eBGP", desc: "同じAS内のBGP接続 / 異なるAS間のBGP接続", src: [[6, "午後Ⅰ 問2"], [5, "午後Ⅱ 問1"]] },
  { field: "ip", term: "IX", desc: "インターネットエクスチェンジ。複数のASが相互接続する場所", src: [[6, "午後Ⅰ 問1"]] },
  { field: "ip", term: "トランジット ISP", desc: "他のASへの通信を中継して，インターネット全体へ届けるISP", src: [[6, "午後Ⅰ 問1"]] },
  { field: "ip", term: "ルーティングループ", desc: "パケットがルータ間を回り続ける状態。TTL切れまで転送される", src: [[6, "午後Ⅰ 問2"], [5, "午後Ⅱ 問1"]] },

  // ---- WAN・VPN ----
  { field: "wan", term: "PPP の認証", desc: "リンク確立フェーズの後にPAPやCHAPで認証する", src: [[7, "午前Ⅱ 問9"]] },
  { field: "wan", term: "ESP トンネルモード", desc: "元のIPヘッダを含むパケット全体とESPトレーラを暗号化", src: [[6, "午前Ⅱ 問21"], [5, "午前Ⅱ 問9"]] },
  { field: "wan", term: "IKE", desc: "IPsecの鍵交換。UDP 500（NATトラバーサル時は4500）", src: [[6, "午前Ⅱ 問21"]] },
  { field: "wan", term: "IKEv2", desc: "4つのメッセージでIKE SAとIPsec SAを確立する", src: [[7, "午後Ⅱ 問2"]] },
  { field: "wan", term: "事前共有鍵", desc: "IPsecのペアで共有する鍵。ペアごとに変えると漏えいの影響が小さい", src: [[6, "午後Ⅰ 問3"]] },
  { field: "wan", term: "ハブアンドスポーク", desc: "本社をハブ，拠点をスポークとするVPN構成", src: [[6, "午後Ⅰ 問3"]] },
  { field: "wan", term: "IP Unnumbered", desc: "インタフェースにIPアドレスを割り当てずに使う設定", src: [[6, "午後Ⅰ 問3"]] },
  { field: "wan", term: "トンネルとフラグメント", desc: "MTU超えで分割が起き負荷が増す。TCPのMSS調整で防ぐ", src: [[6, "午後Ⅰ 問3"]] },
  { field: "wan", term: "ローカルブレイクアウト", desc: "拠点から直接インターネットへ出し，本社の負荷を減らす", src: [[6, "午後Ⅰ 問3"]] },
  { field: "wan", term: "SD-WAN", desc: "コントローラーが経路やIPsec情報を配り，アプリごとに回線を選ぶ", src: [[6, "午後Ⅰ 問2"]] },
  { field: "wan", term: "BFD", desc: "トンネルやリンクの障害を高速に検出する", src: [[6, "午後Ⅰ 問2"]] },
  { field: "wan", term: "CE ルータ", desc: "通信事業者のPEルータと向かい合う利用者側のルータ", src: [[6, "午後Ⅰ 問2"]] },
  { field: "wan", term: "マルチホーム接続", desc: "複数の回線で同じ網につなぎ，可用性を高める", src: [[5, "午後Ⅱ 問1"]] },
  { field: "wan", term: "IPsec の SA", desc: "暗号化通信のトンネル。1方向なので送受信で2本必要", src: [[7, "午後Ⅱ 問2"]] },
  { field: "wan", term: "オーバーレイ / アンダーレイ", desc: "物理網の上に作る論理網 / その土台となる物理網", src: [[6, "午後Ⅰ 問2"]] },
  { field: "wan", term: "IP-IP カプセル化", desc: "IPパケットを別のIPヘッダで包んでトンネルを作る", src: [[6, "午後Ⅰ 問3"]] },

  // ---- 冗長化・負荷分散 ----
  { field: "red", term: "VRRP", desc: "複数ルータで仮想IPを共有し，デフォルトゲートウェイを冗長化", src: [[7, "午後Ⅰ 問1"], [5, "午後Ⅱ 問1"]] },
  { field: "red", term: "プリエンプトディレイ", desc: "経路が収束するまで待ってからマスターに戻す設定", src: [[7, "午後Ⅰ 問1"]] },
  { field: "red", term: "VRRP は BGP の後", desc: "経路を持たないルータがマスターになると転送できないため", src: [[5, "午後Ⅱ 問1"]] },
  { field: "red", term: "DNS ラウンドロビン", desc: "1つの名前に複数のIPアドレスを登録して負荷分散する", src: [[5, "午後Ⅱ 問1"], [6, "午後Ⅱ 問2"]] },
  { field: "red", term: "DNS の TTL", desc: "キャッシュを保持する時間。短くすると変更がすぐ反映される", src: [[5, "午後Ⅱ 問1"]] },
  { field: "red", term: "L7 ヘルスチェック", desc: "HTTPで確認し，アプリの停止まで検知できる（pingでは不可）", src: [[6, "午後Ⅰ 問1"], [5, "午後Ⅱ 問2"]] },
  { field: "red", term: "最少接続数方式", desc: "同時接続数が最も少ないサーバに振り分ける", src: [[6, "午後Ⅰ 問1"]] },
  { field: "red", term: "スケールアウト / アップ", desc: "台数を増やす / 性能を上げる。アウトは無停止で増強できる", src: [[5, "午後Ⅱ 問2"]] },
  { field: "red", term: "仮想 IP アドレス", desc: "LBが負荷分散用に受け付けるアドレス。DNSはこれを指す", src: [[5, "午後Ⅱ 問2"]] },
  { field: "red", term: "ソース NAT（LB）", desc: "送信元をLBに変換。サーバのゲートウェイ変更が不要になる", src: [[5, "午後Ⅱ 問2"]] },
  { field: "red", term: "Cookie でセッション維持", desc: "セッションIDで同じサーバへ。IPやポート番号では不十分", src: [[5, "午後Ⅱ 問2"]] },
  { field: "red", term: "TLS を LB で終端", desc: "サーバ証明書と秘密鍵をLBに移し，LBで復号する", src: [[5, "午後Ⅱ 問2"], [6, "午後Ⅰ 問1"]] },
  { field: "red", term: "CDN", desc: "分散配置したサーバから配信。DDoSの影響も軽減できる", src: [[6, "午前Ⅱ 問16"], [6, "午後Ⅰ 問1"]] },
  { field: "red", term: "MTBF / MTTR", desc: "平均故障間隔 / 平均修復時間。エラーログはMTTR短縮に効く", src: [[7, "午前Ⅱ 問23"]] },
  { field: "red", term: "ステージング環境", desc: "本番とほぼ同じ構成でリリース前の最終テストを行う環境", src: [[7, "午前Ⅱ 問25"]] },
  { field: "red", term: "1台多い構成", desc: "1台故障しても性能が落ちないよう必要数より1台多く置く", src: [[5, "午後Ⅱ 問2"]] },
  { field: "red", term: "VRRP マスターの選出", desc: "優先度が最も高いルータがマスター。仮想IPを持って転送する", src: [[7, "午後Ⅰ 問1"]] },
  { field: "red", term: "切り戻し", desc: "作業で問題が出たときに元の状態へ戻すこと。IF閉塞なら素早い", src: [[7, "午後Ⅰ 問1"]] },
  { field: "red", term: "静的 NAT", desc: "グローバルIPとプライベートIPを1対1で固定的に変換する", src: [[6, "午後Ⅱ 問2"], [5, "午後Ⅱ 問2"]] },

  // ---- プロトコル・アプリ ----
  { field: "app", term: "CoAP", desc: "IoT向けのUDPベースのプロトコル。損失の多い環境・小電力向け", src: [[7, "午前Ⅱ 問5"], [5, "午前Ⅱ 問8"], [7, "午後Ⅱ 問2"]] },
  { field: "app", term: "CoAP のトークン / メッセージID", desc: "要求と応答の対応付け / 重複メッセージの検出", src: [[7, "午後Ⅱ 問2"]] },
  { field: "app", term: "HTTP の GET と POST", desc: "入力値をGETはリクエスト行に，POSTはボディに入れる", src: [[7, "午前Ⅱ 問6"]] },
  { field: "app", term: "HTTP/2 のストリーム", desc: "1つのTCPコネクションで要求と応答を多重化する通信路", src: [[7, "午後Ⅰ 問2"], [5, "午後Ⅰ 問1"]] },
  { field: "app", term: "HoL ブロッキング", desc: "先頭の処理が終わるまで後続が待たされる問題", src: [[7, "午後Ⅰ 問2"], [5, "午後Ⅰ 問1"]] },
  { field: "app", term: "HPACK", desc: "HTTP/2のヘッダー圧縮。:method，:scheme，:path が必須", src: [[5, "午後Ⅰ 問1"]] },
  { field: "app", term: "ALPN", desc: "TLSの拡張。通信開始時に上位プロトコル（h2など）を決める", src: [[5, "午後Ⅰ 問1"]] },
  { field: "app", term: "リバースプロキシ", desc: "外部からの要求を受けて背後のサーバへ中継する", src: [[5, "午後Ⅰ 問1"]] },
  { field: "app", term: "権威 DNS / キャッシュ DNS", desc: "自ドメインの情報を返す / 問合せを代わりに解決して保持する", src: [[5, "午後Ⅰ 問1"]] },
  { field: "app", term: "MX の Preference", desc: "値が小さいメールサーバほど優先される", src: [[6, "午後Ⅱ 問2"]] },
  { field: "app", term: "逆引き（PTR）", desc: "IPからホスト名を得る。攻撃者も自由に設定できる", src: [[6, "午後Ⅱ 問2"]] },
  { field: "app", term: "EDNS", desc: "DNSの512バイト制限を拡張する。非対応ならTCPを使う", src: [[7, "午後Ⅱ 問1"]] },
  { field: "app", term: "DHCP リレーエージェント", desc: "別セグメントのDHCPサーバへ中継。giaddrでセグメントを識別", src: [[7, "午後Ⅰ 問2"], [5, "午後Ⅰ 問3"]] },
  { field: "app", term: "NAT 変換テーブル", desc: "NAPTの対応表。エントリー上限で同時に使える通信数が決まる", src: [[7, "午後Ⅰ 問2"]] },
  { field: "app", term: "帯域確保型", desc: "契約帯域を確保する接続サービス（↔ ベストエフォート型）", src: [[7, "午後Ⅰ 問2"]] },
  { field: "app", term: "PAC ファイル", desc: "宛先に応じて使うプロキシかDIRECTを返す設定ファイル", src: [[6, "午後Ⅰ 問3"], [5, "午後Ⅱ 問1"]] },
  { field: "app", term: "WPAD", desc: "DHCPやDNSでPACファイルのURLを配る仕組み", src: [[6, "午後Ⅰ 問3"]] },
  { field: "app", term: "FTP の PASV", desc: "サーバのデータ用ポートを聞き，クライアントから接続する", src: [[7, "午前Ⅱ 問14"]] },
  { field: "app", term: "TCP の LISTEN", desc: "サーバが接続要求（SYN）を待ち受けている状態", src: [[7, "午前Ⅱ 問11"]] },
  { field: "app", term: "TCP のシーケンス番号", desc: "続けて送るときは 直前の番号＋送信データのオクテット数", src: [[6, "午前Ⅱ 問9"]] },
  { field: "app", term: "MSS 1,460", desc: "MTU 1,500 − IPヘッダ20 − TCPヘッダ20", src: [[5, "午前Ⅱ 問5"]] },
  { field: "app", term: "BBR", desc: "帯域と往復時間を推定するTCPの輻輳制御アルゴリズム", src: [[5, "午前Ⅱ 問4"]] },
  { field: "app", term: "WebDAV", desc: "HTTPを拡張し，サーバ上のファイルを作成・削除・管理する", src: [[5, "午前Ⅱ 問13"]] },
  { field: "app", term: "呼量（アーラン）", desc: "呼数 × 平均保留時間 ÷ 観測時間", src: [[7, "午前Ⅱ 問1"], [6, "午前Ⅱ 問3"]] },
  { field: "app", term: "G.729 のペイロード", desc: "8kbit/s で20ミリ秒ごとなら，1パケット20バイト", src: [[6, "午前Ⅱ 問2"]] },
  { field: "app", term: "R値", desc: "ノイズ・エコー・遅延から算出するIP電話の音声品質の指標", src: [[6, "午前Ⅱ 問15"]] },
  { field: "app", term: "SAML", desc: "IdPが発行するアサーションでSPにログインするSSOの仕組み", src: [[5, "午後Ⅱ 問2"]] },
  { field: "app", term: "IdP / SP", desc: "認証情報を提供する側 / サービスを提供する側", src: [[5, "午後Ⅱ 問2"]] },
  { field: "app", term: "SAML の署名検証", desc: "信頼するIdPが作ったこと，改ざんがないことを確かめる", src: [[5, "午後Ⅱ 問2"]] },
  { field: "app", term: "ケルベロス認証", desc: "KDCがTGTとSTを発行。STはサーバの鍵で暗号化される", src: [[5, "午後Ⅱ 問2"]] },
  { field: "app", term: "X-Forwarded-For", desc: "LBやプロキシが元の送信元IPをサーバへ伝えるヘッダー", src: [[5, "午後Ⅱ 問2"]] },
  { field: "app", term: "証明書のコモン名", desc: "URLのドメインと一致しないとTLSで警告が出る", src: [[5, "午後Ⅱ 問2"]] },
  { field: "app", term: "NTP で時刻合わせ", desc: "複数機器のログを時系列で突き合わせられるようにする", src: [[7, "午後Ⅰ 問3"]] },
  { field: "app", term: "CoAP の CON / ACK", desc: "確認型メッセージと応答。届かなければ指数バックオフで再送", src: [[7, "午後Ⅱ 問2"]] },
  { field: "app", term: "RESTful", desc: "URLで資源を表しGET・POSTなどで操作するAPIの設計形式", src: [[7, "午後Ⅱ 問2"]] },
  { field: "app", term: "HTTP/3 と UDP の保持時間", desc: "HTTP/3はUDP。NATのUDP保持時間を短くしてテーブルを節約", src: [[7, "午後Ⅰ 問2"]] },
  { field: "app", term: "ベストエフォート型", desc: "帯域の保証がないインターネット接続サービス", src: [[7, "午後Ⅰ 問2"]] },
  { field: "app", term: "ストリームID", desc: "HTTP/2で各ストリームを識別する番号。並列処理を可能にする", src: [[7, "午後Ⅰ 問2"]] },
  { field: "app", term: "ビット誤り率の計算", desc: "誤る電文数 ≒ 誤り率 × 1電文のビット数 × 電文数", src: [[7, "午前Ⅱ 問3"], [5, "午前Ⅱ 問6"]] },
  { field: "app", term: "呼損率", desc: "回線が埋まっていて接続できない呼の割合。回線数の設計に使う", src: [[6, "午前Ⅱ 問3"]] },
  { field: "app", term: "DHCP のリースログ", desc: "FWのログのIPアドレスから，どのPCかを特定するときに見る", src: [[7, "午後Ⅰ 問3"]] },
  { field: "app", term: "NS / MX レコード", desc: "ドメインの権威DNSサーバ / メールの配送先サーバを示す", src: [[5, "午後Ⅱ 問2"]] },
  { field: "app", term: "SMTP の MAIL FROM", desc: "エンベロープの送信元アドレス。SPFはこのドメインで照合する", src: [[6, "午後Ⅱ 問2"]] },
  { field: "app", term: "SAML アサーション", desc: "IdPが作る認証・属性・権限の情報を記したXML文書", src: [[5, "午後Ⅱ 問2"]] },
  { field: "app", term: "TGT / ST", desc: "利用者の身分証明のチケット / サーバで認証を受けるチケット", src: [[5, "午後Ⅱ 問2"]] },

  // ---- セキュリティ ----
  { field: "sec", term: "テンペスト攻撃", desc: "漏れる電磁波から表示内容を盗む。対策は電磁波の遮蔽", src: [[7, "午前Ⅱ 問17"]] },
  { field: "sec", term: "DRDoS", desc: "送信元を標的に偽装して多数のサーバに要求し，応答で攻撃する", src: [[7, "午前Ⅱ 問18"], [7, "午後Ⅱ 問2"]] },
  { field: "sec", term: "WPA3-Enterprise", desc: "IEEE 802.1Xの認証と動的な暗号鍵で暗号化する", src: [[7, "午前Ⅱ 問19"]] },
  { field: "sec", term: "EAP-TLS", desc: "認証にクライアント証明書が必要なEAP", src: [[5, "午前Ⅱ 問19"]] },
  { field: "sec", term: "RADIUS", desc: "認証情報やアカウンティング情報をやり取りするプロトコル", src: [[6, "午前Ⅱ 問8"]] },
  { field: "sec", term: "DNSSEC", desc: "デジタル署名で応答の正当性と完全性を検証する", src: [[7, "午前Ⅱ 問20"]] },
  { field: "sec", term: "OP25B", desc: "動的IPから外部の25番ポートへの直接通信を遮断する", src: [[7, "午前Ⅱ 問21"], [5, "午前Ⅱ 問20"]] },
  { field: "sec", term: "SPF", desc: "送信を許可するサーバのIPをDNSに登録して照合する", src: [[6, "午前Ⅱ 問19"], [6, "午後Ⅱ 問2"]] },
  { field: "sec", term: "DKIM", desc: "メールに電子署名を付け，DNSの公開鍵で検証する", src: [[6, "午後Ⅱ 問2"]] },
  { field: "sec", term: "DMARC", desc: "SPF・DKIMの結果に応じた処理方針をDNSで示す", src: [[6, "午前Ⅱ 問19"]] },
  { field: "sec", term: "RLO", desc: "文字の表示順を変える制御文字で拡張子を偽装する手口", src: [[6, "午前Ⅱ 問17"]] },
  { field: "sec", term: "サイドチャネル攻撃", desc: "処理時間や消費電力から内部の秘密情報を推定する", src: [[6, "午前Ⅱ 問18"]] },
  { field: "sec", term: "ビヘイビア法", desc: "マルウェアの動作（書込み・通信など）を監視して検出する", src: [[6, "午前Ⅱ 問20"]] },
  { field: "sec", term: "ポリモーフィック型", desc: "感染ごとに暗号化の鍵を変えてパターン検知を逃れる", src: [[5, "午前Ⅱ 問16"]] },
  { field: "sec", term: "monlist の無効化", desc: "NTPサーバが増幅攻撃の踏み台にされるのを防ぐ", src: [[5, "午前Ⅱ 問17"]] },
  { field: "sec", term: "インライン型 IPS", desc: "通信経路上に置き，異常と合致する通信を遮断する", src: [[5, "午前Ⅱ 問18"]] },
  { field: "sec", term: "SWG", desc: "クラウドのプロキシ。HTTPS検査のためルート証明書をPCに入れる", src: [[7, "午後Ⅰ 問3"]] },
  { field: "sec", term: "C&C サーバ", desc: "遠隔操作型マルウェアが命令を受け取るための通信先", src: [[7, "午後Ⅰ 問3"]] },
  { field: "sec", term: "DTLS の cookie", desc: "送信元が偽装されていないか確かめ，リフレクション攻撃を防ぐ", src: [[7, "午後Ⅱ 問2"]] },
  { field: "sec", term: "TLS のクライアント証明書", desc: "ICカードにも格納でき，使うPCを1台に限らなくてよい", src: [[7, "午前Ⅱ 問16"]] },
  { field: "sec", term: "IEEE 802.1X", desc: "APやスイッチがEAPでクライアントを認証する枠組み", src: [[5, "午前Ⅱ 問21"]] },
  { field: "sec", term: "サンドボックス", desc: "隔離した環境でファイルを動かし，振る舞いを観察する", src: [[7, "午後Ⅰ 問3"]] },
  { field: "sec", term: "IPv6 と NAPT", desc: "IPv6はNAPTを使わない。FWでの通信制御が重要になる", src: [[7, "午後Ⅱ 問1"]] },
  { field: "sec", term: "DKIM のセレクター", desc: "同じドメインで複数の鍵を使い分けるための名前", src: [[6, "午後Ⅱ 問2"]] },
  { field: "sec", term: "S/MIME", desc: "電子メールの暗号化と電子署名を行う規格", src: [[6, "午後Ⅱ 問2"]] },
  { field: "sec", term: "SPF の -all", desc: "登録以外のサーバから送られたメールを認証失敗とする", src: [[6, "午後Ⅱ 問2"]] },
  { field: "sec", term: "OSPF・BGP の認証", desc: "ルータ間で共通の鍵を設定し，不正な経路交換を防ぐ", src: [[7, "午後Ⅰ 問1"], [6, "午後Ⅰ 問1"]] },

  // ---- IT基礎 ----
  { field: "etc", term: "ライトスルー / ライトバック", desc: "主記憶にも同時に書く / 追い出すときに書き戻す", src: [[7, "午前Ⅱ 問22"]] },
  { field: "etc", term: "ブローカー", desc: "分散環境でサービスの登録・検索・仲介を行うパターン", src: [[7, "午前Ⅱ 問24"]] },
  { field: "etc", term: "PCI Express の世代", desc: "世代が上がるごとに1レーンの転送レートが2倍", src: [[6, "午前Ⅱ 問22"]] },
  { field: "etc", term: "フールプルーフ", desc: "誤った入力・操作をしても誤動作しないようにする設計", src: [[6, "午前Ⅱ 問24"]] },
  { field: "etc", term: "メモリインタリーブ", desc: "主記憶を複数バンクに分けて並列にアクセスする", src: [[5, "午前Ⅱ 問22"]] },
  { field: "etc", term: "FaaS", desc: "サーバ管理を意識せずに関数の実行環境を使えるクラウド", src: [[5, "午前Ⅱ 問23"]] },
  { field: "etc", term: "マッシュアップ", desc: "他サイトの機能（API）を組み合わせて新しいサービスを作る", src: [[5, "午前Ⅱ 問25"]] },
  { field: "etc", term: "ターンアラウンドタイム", desc: "ジョブが到着してから実行が終わるまでの時間", src: [[6, "午前Ⅱ 問23"]] },
  { field: "etc", term: "バグトラッキングシステム", desc: "バグの内容や修正計画・修正履歴を記録して管理する", src: [[6, "午前Ⅱ 問25"]] },
  { field: "etc", term: "SysML", desc: "UMLを拡張した，システム設計・検証用のモデリング言語", src: [[5, "午前Ⅱ 問24"]] },
  { field: "etc", term: "フェールセーフ / フェールソフト", desc: "故障時に安全側へ止める / 機能を落としても動かし続ける", src: [[6, "午前Ⅱ 問24"]] },
];
